import { useState } from "react";
import { api } from "../lib/api.js";
import { ErrorNote } from "./ui.jsx";
import { markdown, safeUrl, sourceDate } from "./BriefReading.jsx";
const originName={internal:"自有内容与已有知识",manual:"手动记录",external:"外部资料",owned:"自有内容",self_owned:"自有内容",local:"已有知识",local_knowledge:"已有知识",unknown:"身份待核对"};
const completeness = item => item.contentStatus || item.content_status || (item.readLevel === "summary" ? "summary_only" : "");
const unavailable = item => ["deleted","expired","removed","tombstone","purged","unavailable"].includes(completeness(item)) || Boolean(item.deletedAt || item.deleted_at) || Boolean(item.expiresAt && Date.parse(item.expiresAt) <= Date.now());
const contentLabel = item => unavailable(item) ? "已清除／已到期" : ({full_text:"全文",fulltext:"全文",transcript:"转录",short_content:"短内容",short:"短内容",summary:"摘要",summary_only:"仅摘要",metadata:"仅元数据",metadata_only:"仅元数据",body_failed:"正文失败",failed:"正文失败",unreadable:"不可读",content_failed:"正文失败"}[item.processing?.readability || completeness(item)] || (item.readLevel==="original" ? "已取得全文" : item.readLevel==="summary" ? "仅摘要" : "正文范围待核对"));
const groupNames = {aihot:"AIHOT",t2_media:"T2 媒体",community:"社区",follow_builders:"Follow Builders",legacy:"其他来源"};
const when = value => value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}) : '未提供';
const typeName = item => item.sourceGroup==='aihot' ? ({selected:'精选',hot:'热点事件','hot-topics':'热点事件',daily:'日报'}[item.stream] || 'AIHOT 情报') : item.platform==='x' ? 'X 动态' : ({podcast_transcript:'Podcast Transcript',external_digest:'日报 / Digest',comment:'评论',post:'帖子',tweet:'X 动态',article:'文章',hot_topic:'热点事件'}[item.sourceKind] || item.sourceKind || ({'feed-blogs.json':'博客文章','feed-podcasts.json':'播客','feed-x.json':'X 动态'}[item.stream]) || item.stream || '资料');
function CommentTree({comments,rootId}) {
  const [bucket,setBucket]=useState("all");
  const buckets=comment=>comment.metadata?.sortBuckets || comment.metadata?.sort_buckets || (comment.metadata?.sort_bucket ? [comment.metadata.sort_bucket] : []);
  const byId = new Map(comments.flatMap(c=>[[c.id,c],[c.identity || c.platformId || c.platform_id,c]]).filter(([key])=>key));
  const depthOf = comment => { if(Number.isInteger(comment.depth ?? comment.metadata?.depth))return Math.min(8,comment.depth ?? comment.metadata.depth);if(!(comment.parentItemId || comment.parentIdentity || comment.parent_item_id || comment.parentId))return null;let depth=0,node=comment;const visited=new Set();while(node && depth<8){const parent=node.parentItemId || node.parentIdentity || node.parent_item_id || node.parentId; if(!parent || parent===rootId || visited.has(parent))break;visited.add(parent);node=byId.get(parent);if(node)depth++;}return depth; };
  return <section className="acquisition-comments"><h3>评论与回复上下文</h3><p className="intel-v2-hint">评论是用户观察和研究线索，同一讨论不会作为多份独立事实证据。</p><label>评论排序<select aria-label="评论排序" value={bucket} onChange={e=>setBucket(e.target.value)}><option value="all">全部评论与回复</option><option value="top">Top / Confidence</option><option value="controversial">Controversial</option><option value="new">New</option></select></label>{comments.filter(comment=>bucket==="all" || buckets(comment).includes(bucket) || (bucket==="top" && buckets(comment).includes("confidence"))).map(comment=>{const parent=comment.parentItemId || comment.parentIdentity || comment.parent_item_id || comment.parentId;const missing=parent && parent!==rootId && !byId.has(parent);return <div key={comment.id || comment.identity} className="acquisition-comment" style={{"--comment-depth":depthOf(comment) ?? 0}}><header>{comment.author || "作者信息不可用"} · {sourceDate(comment.publishedAt) || "原始日期未提供"}{comment.metadata?.score!==undefined ? ` · 评分 ${comment.metadata.score}` : ""}{buckets(comment).length ? ` · ${buckets(comment).join(" / ")}` : ""} · 层级 {depthOf(comment) ?? '未知'}</header>{(!parent || missing) && <p className="intel-channel-error">父级关系或上下文尚未取得</p>}<details className="acquisition-comment-relation"><summary>评论关系</summary><p>Root: {comment.rootItemId || comment.root_item_id || rootId}<br/>Parent: {parent || "—"}<br/>Depth: {depthOf(comment) ?? '未知'}</p></details><div>{unavailable(comment) ? "评论已删除或保留期已到，不再展示内容。" : completeness(comment)==="context_missing" ? "这条父级上下文尚未取得，不能据此推断原帖内容。" : markdown(comment.body || "没有可展示的评论正文")}</div>{safeUrl(comment.url) && <a href={safeUrl(comment.url)} target="_blank" rel="noreferrer">查看评论 ↗</a>}</div>;})}</section>;
}
export function AcquisitionResource({item,onGo,onLink}) {
  const isSeed=item.type==="seed",isBrief=item.type==="brief";
  const [full,setFull]=useState(null),[extra,setExtra]=useState(null),[error,setError]=useState(null),[loading,setLoading]=useState(false);
  async function read(force=false){
    if(isSeed || isBrief || (full && !force) || loading)return;setLoading(true);
    try {
      const response=await fetch(`/api/workspace/acquisition/sources/${encodeURIComponent(item.id)}`);
      if(response.status===404){const result=await api.intelligenceSourceDetail(item.id);setFull(result.source || result);setExtra(null);}
      else {const result=await response.json();if(!response.ok || result.ok===false)throw new Error(result.error || "读取资料失败");setFull(result.source);setExtra(result);}
      setError(null);
    }catch(e){setError(e);}finally{setLoading(false);}
  }
  async function supplement(){setLoading(true);try{const r=await fetch('/api/workspace/acquisition/sources/'+encodeURIComponent(item.id)+'/fulltext',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({confirmed:true})});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'正文补全失败');setExtra(previous=>({...previous,bodyDelivery:{status:'queued'}}));setError(null);}catch(e){setError(e);}finally{setLoading(false);}}
  if(isBrief)return <article className="intel-v2-resource"><h2><button className="text-action" onClick={()=>onGo("intel-detail",item.id)}>{item.title}</button></h2><p className="intel-v2-hint">收藏情报 · {sourceDate(item.editionDate || item.createdAt)}</p><p>{item.summary}</p></article>;
  const source={...item,...(full || {}),processing:full?.processing || item.processing}, gone=unavailable(source), body=full ? full.body || full.summary || "尚未取得正文" : item.body || item.summary || "尚无正文";
  const rights=source.rights || {}, discoveries=[...(item.discoveries || []),...(extra?.discoveries || [])].filter((d,i,a)=>a.findIndex(x=>(x.channel_id || x.channelId || x.id)===(d.channel_id || d.channelId || d.id)&&(x.discovery_key || x.discoveryKey)===(d.discovery_key || d.discoveryKey))===i), comments=(extra?.comments || []).filter(c=>c.sourceKind==="comment" || c.contentKind==="comment"), segments=extra?.segments || [];
  return <details className="intel-v2-resource" onToggle={event=>{if(event.currentTarget.open)void read();}}><summary><strong>{isSeed ? item.take : item.title}</strong><span>{isSeed ? "灵感种子" : item.provider==="manual" ? "手动资料" : item.acquisitionBatch ? `${groupNames[item.sourceGroup] || item.sourceGroup || item.platform} · ${(item.sourceGroup==='aihot' ? ({selected:'精选',hot:'热点','hot-topics':'热点',daily:'日报'}[item.stream] || item.channelName || item.stream) : item.sourceGroup==='follow_builders' ? `${({'feed-x.json':'X','feed-podcasts.json':'Podcast','feed-blogs.json':'Blog'}[item.stream] || item.stream)} · ${item.author || '发布者未提供'}` : item.channelName || item.author || item.stream) || ""}` : originName[item.originKind || item.originType] || "身份待核对"} · {sourceDate(item.publishedAt) || "原始日期未提供"}{!isSeed ? ` · ${contentLabel(source)}` : ""}{(item.sourceKind || item.contentKind)==="comment" ? " · 评论（同一讨论不算独立证据）" : ""}</span>    {item.acquisitionBatch && <div className="acquisition-item-facts"><span>内容类型：{typeName(item)}</span><span>发布时间：{when(item.publishedAt)}</span><span>最近检查：{when(item.lastSeenAt)}</span><span>正文状态：{contentLabel(source)}</span><span>{item.dedupResult==='inserted' || item.dedupResult==='new' ? '本轮新增' : item.dedupResult==='updated' ? '本轮更新' : item.dedupResult || ''}</span></div>}

</summary>
    {loading && <p role="status">正在读取正文…</p>}{error && <ErrorNote error={error} what="读取资料" onRetry={read}/>}
    {!isSeed && (source.acquisition || source.processing) && <div className="acquisition-resource-meta"><span>{source.platform || source.provider}</span><span>{rights.aiAllowed===true ? "已允许 AI 处理" : "外部 AI 处理未授权"}</span><span>{rights.exportAllowed===true ? "已允许导出" : "导出未授权"}</span>{source.expiresAt && <span>保留至 {sourceDate(source.expiresAt)}</span>}</div>}
    {!isSeed && (source.sourceKind==="external_digest" || source.metadata?.secondarySource) && <p className="intel-v2-hint">这是上游整理的报告，报告中的摘要和判断需结合所引原文核对。</p>}
    {!gone && /podcast|transcript/.test(source.sourceKind || item.sourceKind || source.platform || '') && <p className="intel-v2-hint">{contentLabel(source)} · {full ? Array.from(full.body || '').length.toLocaleString('zh-CN') : '读取后显示'} 字符{full ? '（完整正文字符数）' : ''}</p>}
    {!gone && (source.platform==='x' || item.platform==='x') && <p className="intel-v2-hint">@{source.author || item.author || '作者未提供'} · likes {source.metadata?.likes ?? source.metadata?.metrics?.likes ?? item.metadata?.likes ?? '—'} · reposts {source.metadata?.reposts ?? source.metadata?.retweets ?? source.metadata?.metrics?.reposts ?? '—'} · replies {source.metadata?.replies ?? source.metadata?.metrics?.replies ?? '—'}</p>}
    {isSeed ? <p className="intel-resource-body">{item.sourceTitle || item.trigger || item.body || item.take}</p> : gone ? <p>这条资料已删除或保留期已到，正文不再展示。</p> : <>
      {source.processing?.guide && <section className="acquisition-reading-guide"><h3>中文导读 · {source.processing.guideKind==='extractive' || source.processing.guideKind==='deterministic' ? '本地摘录' : '机器生成候选'}</h3>{markdown(source.processing.guide)}<p className="intel-v2-hint">导读与原始内容分别保存，请核对下面的依据。</p>{(source.processing.guideEvidence || []).map((entry,index)=><div key={index}>{typeof entry==='string' ? <blockquote>{entry}</blockquote> : <><p>{entry.text}</p>{(entry.quotes || [entry.quote || entry.excerpt].filter(Boolean)).map((quote,quoteIndex)=><blockquote key={quoteIndex}>{quote}</blockquote>)}</>}</div>)}</section>}
      <section className="acquisition-reading-body"><h3>{source.processing?.readingBody ? '阅读版本' : '已取得的原始材料'}</h3>{markdown(source.processing?.readingBody || body)}</section>
      {source.processing?.readingBody && <details className="acquisition-raw-body"><summary>核对原始正文</summary>{markdown(body)}</details>}
      {source.processing && <details className="acquisition-detail-fields"><summary>相关性与完整度依据</summary><p>{({ai_relevant:'与 AI 直接相关',needs_context:'主题待补上下文',not_ai:'已过滤：无实质 AI 关系'}[source.processing.relevance] || '尚未判断')} · {source.processing.readability || '完整度未知'}</p><p>{source.processing.reason}</p>{(source.processing.evidence || []).map((entry,index)=><blockquote key={index}>{typeof entry==='string' ? entry : entry.quote || entry.text || entry.excerpt}</blockquote>)}<p>规则：{source.processing.ruleVersion} · 正文指纹：{source.processing.contentHash}</p></details>}
    </>}
    {!isSeed && !gone && source.platform!=='reddit' && ['summary','summary_only','metadata','metadata_only','body_failed'].includes(source.processing?.readability || completeness(source)) && <div><p className="intel-v2-hint">访问并保存这篇公开原文，保留原有版本；不会发送给模型。</p><button className="btn" disabled={loading || ['queued','running'].includes(extra?.bodyDelivery?.status)} onClick={supplement}>确认补全公开正文</button></div>}
    {extra?.bodyDelivery && <p role="status">正文补全：{({queued:'已排队',running:'处理中',completed:'已完成',failed:'失败',blocked:'访问受限'}[extra.bodyDelivery.status]||extra.bodyDelivery.status)} {extra.bodyDelivery.error}<button className="text-action" disabled={loading} onClick={()=>read(true)}>刷新正文状态</button></p>}
    {safeUrl(source.url || item.sourceUrl) && <a href={safeUrl(source.url || item.sourceUrl)} target="_blank" rel="noreferrer">查看原文 ↗</a>}
    {!isSeed && <details className="acquisition-detail-fields"><summary>采集详情</summary><dl>{Object.entries({"Source Group":groupNames[source.sourceGroup || item.sourceGroup] || source.sourceGroup || item.sourceGroup,"Stream":source.stream || item.stream,"原始发布者":source.publisher || "未提供","作者":source.author || "未提供","External ID":source.platformId || source.platform_id || source.metadata?.externalId,"原始发布时间":when(source.publishedAt),"上游首次出现":when(source.upstreamFirstSeenAt),"本地首次入库":when(source.firstSeenAt || item.firstSeenAt),"最近检查":when(source.lastSeenAt || item.lastSeenAt),"Acquisition Run ID":item.runId || extra?.runs?.map(r=>r.runId || r.id).join(', '),"Original URL":source.url,"Content State":completeness(source),"Dedup Result":item.dedupResult}).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value || '—'}</dd></div>)}</dl></details>}
    {!!discoveries.length && <section className="acquisition-discoveries"><h3>发现渠道</h3><ul>{discoveries.map((d,index)=><li key={d.id || index}>{d.channelName || d.channel_name || d.name || d.channel_id || d.channelId}{d.discoveredAt || d.discovered_at || d.last_seen_at ? ` · ${sourceDate(d.discoveredAt || d.discovered_at || d.last_seen_at)}` : ""}{d.active===false || d.active===0 || d.selected===0 ? " · 已退出上游精选，原始引用保留" : ""}</li>)}</ul></section>}
    {!gone && !!segments.length && <details className="acquisition-segments"><summary>按段阅读 · {segments.length} 段</summary><p className="intel-v2-hint">同一文档的分段仅用于阅读与引用，不会算成多个独立来源。</p>{segments.map((segment,index)=><section key={segment.id || index}><h4>{segment.speaker || segment.metadata?.speaker || `第 ${index+1} 段`}{(segment.startTime ?? segment.start_time)!=null ? ` · ${segment.startTime ?? segment.start_time}` : ""}</h4>{markdown(segment.text || segment.body || segment.content || (Number.isInteger(segment.start_offset) ? source.body?.slice(segment.start_offset,segment.end_offset) : ""))}</section>)}</details>}
    {!gone && !!comments.length && <CommentTree comments={comments} rootId={source.rootItemId || source.id}/>}
    {!isSeed && <div className="intel-v2-actions"><button className="btn" disabled={gone || loading || Boolean(error)} onClick={()=>onLink?.(source)}>带入选题</button></div>}
  </details>;
}
