import { useState } from "react";
import { api } from "../lib/api.js";
import { ErrorNote } from "./ui.jsx";
import { safeUrl, sourceDate } from "./BriefReading.jsx";
const originName={internal:"自有内容与已有知识",manual:"手动记录",external:"外部资料",owned:"自有内容",self_owned:"自有内容",local:"已有知识",local_knowledge:"已有知识",unknown:"身份待核对"};
const completeness = item => item.contentStatus || item.content_status || (item.readLevel === "summary" ? "summary_only" : "");
const unavailable = item => ["deleted","expired","removed","tombstone","purged","unavailable"].includes(completeness(item)) || Boolean(item.deletedAt || item.deleted_at) || Boolean(item.expiresAt && Date.parse(item.expiresAt) <= Date.now());
const contentLabel = item => unavailable(item) ? "已清除／已到期" : ["full_text","fulltext","transcript"].includes(completeness(item)) || item.readLevel==="original" ? "已取得全文" : completeness(item)==="summary_only" || item.readLevel==="summary" ? "仅摘要" : "正文范围待核对";
const groupNames = {aihot:"AIHOT",t2_media:"T2 媒体",community:"社区",follow_builders:"Follow Builders",legacy:"其他来源"};
const when = value => value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}) : '未提供';
const typeName = item => item.sourceGroup==='aihot' ? ({selected:'精选',hot:'热点事件','hot-topics':'热点事件',daily:'日报'}[item.stream] || 'AIHOT 情报') : item.platform==='x' ? 'X 动态' : ({podcast_transcript:'Podcast Transcript',external_digest:'日报 / Digest',comment:'评论',post:'帖子',tweet:'X 动态',article:'文章',hot_topic:'热点事件'}[item.sourceKind] || item.sourceKind || item.stream || '资料');
function CommentTree({comments,rootId}) {
  const [bucket,setBucket]=useState("all");
  const buckets=comment=>comment.metadata?.sortBuckets || comment.metadata?.sort_buckets || (comment.metadata?.sort_bucket ? [comment.metadata.sort_bucket] : []);
  const byId = new Map(comments.flatMap(c=>[[c.id,c],[c.identity || c.platformId || c.platform_id,c]]).filter(([key])=>key));
  const depthOf = comment => { if(Number.isInteger(comment.depth ?? comment.metadata?.depth))return Math.min(8,comment.depth ?? comment.metadata.depth);let depth=0,node=comment;const visited=new Set();while(node && depth<8){const parent=node.parentItemId || node.parentIdentity || node.parent_item_id || node.parentId; if(!parent || parent===rootId || visited.has(parent))break;visited.add(parent);node=byId.get(parent);if(node)depth++;}return depth; };
  return <section className="acquisition-comments"><h3>评论与回复上下文</h3><p className="intel-v2-hint">评论是用户观察和研究线索，同一讨论不会作为多份独立事实证据。</p><label>评论排序<select aria-label="评论排序" value={bucket} onChange={e=>setBucket(e.target.value)}><option value="all">全部评论与回复</option><option value="top">Top / Confidence</option><option value="controversial">Controversial</option><option value="new">New</option></select></label>{comments.filter(comment=>bucket==="all" || buckets(comment).includes(bucket) || (bucket==="top" && buckets(comment).includes("confidence"))).map(comment=>{const parent=comment.parentItemId || comment.parentIdentity || comment.parent_item_id || comment.parentId;const missing=parent && parent!==rootId && !byId.has(parent);return <div key={comment.id || comment.identity} className="acquisition-comment" style={{"--comment-depth":depthOf(comment)}}><header>{comment.author || "作者信息不可用"} · {sourceDate(comment.publishedAt || comment.created_at)}{comment.metadata?.score!==undefined ? ` · 评分 ${comment.metadata.score}` : ""}{buckets(comment).length ? ` · ${buckets(comment).join(" / ")}` : ""} · 层级 {depthOf(comment)}</header>{missing && <p className="intel-channel-error">父级上下文尚未取得</p>}<details className="acquisition-comment-relation"><summary>评论关系</summary><p>Root: {comment.rootItemId || comment.root_item_id || rootId}<br/>Parent: {parent || "—"}<br/>Depth: {depthOf(comment)}</p></details><p>{unavailable(comment) ? "评论已删除或保留期已到，不再展示内容。" : completeness(comment)==="context_missing" ? "这条父级上下文尚未取得，不能据此推断原帖内容。" : comment.body || "没有可展示的评论正文"}</p>{safeUrl(comment.url) && <a href={safeUrl(comment.url)} target="_blank" rel="noreferrer">查看评论 ↗</a>}</div>;})}</section>;
}
export function AcquisitionResource({item,onGo,onLink}) {
  const isSeed=item.type==="seed",isBrief=item.type==="brief";
  const [full,setFull]=useState(null),[extra,setExtra]=useState(null),[error,setError]=useState(null),[loading,setLoading]=useState(false);
  async function read(){
    if(isSeed || isBrief || full || loading)return;setLoading(true);
    try {
      const response=await fetch(`/api/workspace/acquisition/sources/${encodeURIComponent(item.id)}`);
      if(response.status===404){const result=await api.intelligenceSourceDetail(item.id);setFull(result.source || result);setExtra(null);}
      else {const result=await response.json();if(!response.ok || result.ok===false)throw new Error(result.error || "读取资料失败");setFull(result.source);setExtra(result);}
      setError(null);
    }catch(e){setError(e);}finally{setLoading(false);}
  }
  if(isBrief)return <article className="intel-v2-resource"><h2><button className="text-action" onClick={()=>onGo("intel-detail",item.id)}>{item.title}</button></h2><p className="intel-v2-hint">收藏情报 · {sourceDate(item.editionDate || item.createdAt)}</p><p>{item.summary}</p></article>;
  const source=full || item, gone=unavailable(source), body=full ? full.body || full.summary || "尚未取得正文" : item.body || item.summary || "尚无正文";
  const rights=source.rights || {}, discoveries=extra?.discoveries || [], comments=(extra?.comments || []).filter(c=>c.sourceKind==="comment" || c.contentKind==="comment"), segments=extra?.segments || [];
  return <details className="intel-v2-resource" onToggle={event=>{if(event.currentTarget.open)void read();}}><summary><strong>{isSeed ? item.take : item.title}</strong><span>{isSeed ? "灵感种子" : item.provider==="manual" ? "手动资料" : item.acquisitionBatch ? `${groupNames[item.sourceGroup] || item.sourceGroup || item.platform} · ${(item.sourceGroup==='aihot' ? ({selected:'精选',hot:'热点','hot-topics':'热点',daily:'日报'}[item.stream] || item.channelName || item.stream) : item.sourceGroup==='follow_builders' ? `${({'feed-x.json':'X','feed-podcasts.json':'Podcast','feed-blogs.json':'Blog'}[item.stream] || item.stream)} · ${item.author || '发布者未提供'}` : item.channelName || item.author || item.stream) || ""}` : originName[item.originKind || item.originType] || "身份待核对"} · {sourceDate(item.publishedAt || item.createdAt)}{!isSeed ? ` · ${contentLabel(source)}` : ""}{(item.sourceKind || item.contentKind)==="comment" ? " · 评论（同一讨论不算独立证据）" : ""}</span>    {item.acquisitionBatch && <div className="acquisition-item-facts"><span>内容类型：{typeName(item)}</span><span>发布时间：{when(item.publishedAt)}</span><span>采集时间：{when(item.lastSeenAt || item.firstSeenAt)}</span><span>正文状态：{contentLabel(source)}</span><span>{item.dedupResult==='inserted' || item.dedupResult==='new' ? '本轮新增' : item.dedupResult==='updated' ? '本轮更新' : item.dedupResult || ''}</span></div>}
    {item.acquisitionBatch && !full && <p className="intel-resource-body">{item.body}</p>}
</summary>
    {loading && <p role="status">正在读取正文…</p>}{error && <ErrorNote error={error} what="读取资料" onRetry={read}/>}
    {!isSeed && source.acquisition && <div className="acquisition-resource-meta"><span>{source.platform || source.provider}</span><span>{rights.aiAllowed===true ? "已允许 AI 处理" : "外部 AI 处理未授权"}</span><span>{rights.exportAllowed===true ? "已允许导出" : "导出未授权"}</span>{source.expiresAt && <span>保留至 {sourceDate(source.expiresAt)}</span>}</div>}
    {!isSeed && (source.sourceKind==="external_digest" || source.metadata?.secondarySource) && <p className="intel-v2-hint">这是上游整理的报告，报告中的摘要和判断需结合所引原文核对。</p>}
    {!gone && /podcast|transcript/.test(source.sourceKind || item.sourceKind || source.platform || '') && <p className="intel-v2-hint">{contentLabel(source)} · {full ? Array.from(full.body || '').length.toLocaleString('zh-CN') : '读取后显示'} 字符{full ? '（完整正文字符数）' : ''}</p>}
    {!gone && (source.platform==='x' || item.platform==='x') && <p className="intel-v2-hint">@{source.author || item.author || '作者未提供'} · likes {source.metadata?.likes ?? source.metadata?.metrics?.likes ?? item.metadata?.likes ?? '—'} · reposts {source.metadata?.reposts ?? source.metadata?.retweets ?? source.metadata?.metrics?.reposts ?? '—'} · replies {source.metadata?.replies ?? source.metadata?.metrics?.replies ?? '—'}</p>}
    <p className={`intel-resource-body${!isSeed && body.length>12000 ? " intel-resource-body--long" : ""}`} tabIndex={!isSeed && body.length>12000 ? 0 : undefined} aria-label={!isSeed && body.length>12000 ? "完整正文，可滚动阅读" : undefined}>{isSeed ? item.sourceTitle || item.trigger || item.body || item.take : gone ? "这条资料已删除或保留期已到，正文不再展示。" : body}</p>
    {safeUrl(source.url || item.sourceUrl) && <a href={safeUrl(source.url || item.sourceUrl)} target="_blank" rel="noreferrer">查看原文 ↗</a>}
    {!isSeed && <details className="acquisition-detail-fields"><summary>采集详情</summary><dl>{Object.entries({"Source Group":groupNames[source.sourceGroup || item.sourceGroup] || source.sourceGroup || item.sourceGroup,"Stream":source.stream || item.stream,"Publisher":source.publisher || source.author || item.channelName,"External ID":source.platformId || source.platform_id || source.metadata?.externalId,"Published At":when(source.publishedAt),"First Seen At":when(source.firstSeenAt || source.createdAt || item.firstSeenAt),"Last Seen At":when(source.lastSeenAt || source.updatedAt || item.lastSeenAt),"Acquisition Run ID":item.runId || extra?.runs?.map(r=>r.runId || r.id).join(', '),"Original URL":source.url,"Content State":completeness(source),"Dedup Result":item.dedupResult}).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value || '—'}</dd></div>)}</dl></details>}
    {!!discoveries.length && <section className="acquisition-discoveries"><h3>发现渠道</h3><ul>{discoveries.map((d,index)=><li key={d.id || index}>{d.channelName || d.channel_name || d.name || d.channel_id || d.channelId}{d.discoveredAt || d.discovered_at || d.last_seen_at ? ` · ${sourceDate(d.discoveredAt || d.discovered_at || d.last_seen_at)}` : ""}{d.active===false || d.active===0 || d.selected===0 ? " · 已退出上游精选，原始引用保留" : ""}</li>)}</ul></section>}
    {!gone && !!segments.length && <details className="acquisition-segments"><summary>按段阅读 · {segments.length} 段</summary><p className="intel-v2-hint">同一文档的分段仅用于阅读与引用，不会算成多个独立来源。</p>{segments.map((segment,index)=><section key={segment.id || index}><h4>{segment.speaker || segment.metadata?.speaker || `第 ${index+1} 段`}{segment.startTime || segment.start_time ? ` · ${segment.startTime || segment.start_time}` : ""}</h4><p className="intel-resource-body">{segment.text || segment.body || segment.content || (Number.isInteger(segment.start_offset) ? source.body?.slice(segment.start_offset,segment.end_offset) : "")}</p></section>)}</details>}
    {!gone && !!comments.length && <CommentTree comments={comments} rootId={source.rootItemId || source.id}/>}
    {!isSeed && <div className="intel-v2-actions"><button className="btn" disabled={gone || loading || Boolean(error)} onClick={()=>onLink?.(source)}>带入选题</button></div>}
  </details>;
}
