import { useEffect, useState } from "react";
import { api } from "../lib/api.js";
import { ErrorNote, Loading } from "./ui.jsx";
const labels = { material: "素材", wiki: "知识笔记", source: "原始资料", capture: "记录", seed: "想法" };
export function LibraryBrowser({ onChoose, onGo }) {
  const [q, setQ] = useState(""); const [kind, setKind] = useState(""); const [items, setItems] = useState(null); const [error, setError] = useState(null); const [selected, setSelected] = useState(null);
  useEffect(() => { let alive = true; const timer = setTimeout(() => api.library(q, kind).then((r) => { if (alive) { setItems(r.items || []); setError(null); } }).catch((e) => { if (alive) setError(e); }), 200); return () => { alive = false; clearTimeout(timer); }; }, [q, kind]);
  async function open(item) { try { setSelected((await api.libraryItem(item.kind, item.id)).item); } catch (e) { setError(e); } }
  return <div className="library-browser"><div className="library-search"><input type="search" aria-label="搜索资料" placeholder="找原文、经历或知识笔记" value={q} onChange={(e) => setQ(e.target.value)} /><select aria-label="资料类型" value={kind} onChange={(e) => setKind(e.target.value)}><option value="">全部资料</option>{Object.entries(labels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></div><ErrorNote error={error} what="读取资料" />{items === null && !error ? <Loading rows={3} /> : null}{selected ? <section className="library-original"><button className="btn btn-sm" onClick={() => setSelected(null)}>返回资料列表</button><small>{labels[selected.kind] || selected.kind}</small><h2>{selected.title}</h2><pre>{selected.body || selected.excerpt || "暂无正文"}</pre>{/^https?:\/\//i.test(selected.sourceUrl || "") ? <a href={selected.sourceUrl} target="_blank" rel="noreferrer">打开原始链接</a> : null}{onChoose ? <button className="btn" onClick={() => onChoose(selected)}>关联这份资料</button> : null}{selected.route && onGo ? <button className="btn" onClick={() => onGo(selected.route.view, selected.route.state)}>打开完整记录</button> : null}</section> : <div className="library-results">{(items || []).map((item) => <article key={`${item.kind}:${item.id}`}><button onClick={() => open(item)}><small>{labels[item.kind] || item.kind}</small><h3>{item.title || "未命名记录"}</h3><p>{item.excerpt}</p></button>{onChoose ? <button className="btn btn-sm" onClick={() => onChoose(item)}>关联资料</button> : null}</article>)}</div>}{items && !items.length ? <p className="task-empty">{q ? "没有找到匹配的资料。可以换个关键词。" : "资料会留在这里。先记下一段话，或导入已有资料。"}</p> : null}</div>;
}
