import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { api } from "../lib/api.js";
import { renderMarkdown } from "../lib/markdown.js";
import { AssistantPane } from "./assistant/AssistantPane.jsx";
import { ErrorNote, Loading } from "./ui.jsx";
import "../pages/workspace-home.css";
const labels = { material: "素材", wiki: "Wiki", source: "原始资料", capture: "记录", seed: "想法" };
export function LibraryBrowser({ onChoose, onGo, initialItem }) {
  const [q, setQ] = useState(""), [kind, setKind] = useState(""), [items, setItems] = useState(null), [error, setError] = useState(null), [selected, setSelected] = useState(null), [opening, setOpening] = useState(false);
  const request = useRef(0);
  useEffect(() => { let alive = true; const timer = setTimeout(() => api.library(q, kind).then(r => { if (alive) { setItems(r.items || []); setError(null); } }).catch(e => { if (alive) setError(e); }), 200); return () => { alive = false; clearTimeout(timer); }; }, [q, kind]);
  const open = useCallback(async item => { const ticket = ++request.current; setOpening(true); setError(null); try { const result = await api.libraryItem(item.kind, item.id); if (ticket === request.current) setSelected(result.item); } catch (e) { if (ticket === request.current) setError(e); } finally { if (ticket === request.current) setOpening(false); } }, []);
  useEffect(() => { if (typeof initialItem === "string" && initialItem.includes(":")) { const [kind, ...id] = initialItem.split(":"); if (labels[kind]) open({kind, id:id.join(":")}); } }, [initialItem, open]);
  return <div className="library-browser"><ErrorNote error={error} what="读取资料" />{opening ? <Loading rows={2} /> : null}{selected ? <LibraryReader key={`${selected.kind}:${selected.id}`} item={selected} onChoose={onChoose} onBack={() => { request.current++; setSelected(null); }} /> : <><div className="library-search"><input type="search" aria-label="搜索资料" placeholder="查找原文、笔记或 Wiki" value={q} onChange={e => setQ(e.target.value)} /><select aria-label="资料类型" value={kind} onChange={e => setKind(e.target.value)}><option value="">全部资料</option>{Object.entries(labels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></div>{items === null && !error ? <Loading rows={3} /> : null}<div className="library-card-grid">{(items || []).map(item => <article key={`${item.kind}:${item.id}`}><button onClick={() => onGo && !onChoose ? onGo("library", `${item.kind}:${item.id}`) : open(item)}><small>{labels[item.kind] || item.kind}</small><h3>{item.title || "未命名记录"}</h3><p>{item.excerpt?.replace(/[#*`]/g, "").slice(0, 150)}</p></button>{onChoose ? <button className="btn btn-sm" onClick={() => onChoose(item)}>关联资料</button> : null}</article>)}</div>{items && !items.length ? <p className="task-empty">{q ? "没有找到匹配的资料，可以换个关键词。" : "导入已有资料，或记下一段新的理解。"}</p> : null}</>}</div>;
}
function LibraryReader({ item, onChoose, onBack }) {
  const [ai, setAi] = useState(false), [mounted, setMounted] = useState(false), [selection, setSelection] = useState(""), [prompt, setPrompt] = useState(null), [error, setError] = useState(null), [topics, setTopics] = useState(null), [topicId, setTopicId] = useState(""), [status, setStatus] = useState(""), [busy, setBusy] = useState(false);
  const bodyRef = useRef(null), restore = useRef(null), timer = useRef(null), ready = useRef(false), lastPosition = useRef(null);
  const html = useMemo(() => renderMarkdown(item.body || item.excerpt || "暂无正文"), [item]);
  useEffect(() => {
    let active = true;
    api.workspaceActivity().then(result => {
      if (!active) return;
      restore.current = result.reading?.find(x => x.id === item.id && x.kind === item.kind)?.position; lastPosition.current = restore.current;
      const el = bodyRef.current; if (el) el.scrollTop = restore.current?.scrollTop || 0;
      ready.current = true;
      return api.recordActivity(item.kind, item.id, { mode: "read", ...(restore.current ? {position: restore.current} : {}) });
    }).catch(setError);
    return () => { active = false; clearTimeout(timer.current); if (ready.current && lastPosition.current) api.recordActivity(item.kind, item.id, { mode: "read", position: lastPosition.current }).catch(() => {}); };
  }, [item.id, item.kind]);
  function track() { if (!ready.current) return; clearTimeout(timer.current); const el = bodyRef.current; const position = { scrollTop: el.scrollTop, progress: el.scrollHeight <= el.clientHeight ? 1 : el.scrollTop / (el.scrollHeight - el.clientHeight) }; lastPosition.current = position; timer.current = setTimeout(() => api.recordActivity(item.kind, item.id, {mode:"read",position}).catch(setError), 500); }
  function captureSelection() { const range = window.getSelection(); setSelection(range && bodyRef.current?.contains(range.anchorNode) && bodyRef.current?.contains(range.focusNode) ? range.toString().trim().slice(0, 8000) : ""); }
  function discuss(quoted = false) { setMounted(true); setAi(true); if (quoted && selection) setPrompt({id: crypto.randomUUID(), text: `请结合原文解释下面这段话，区分原文观点和你的推断：\n\n${selection}`}); }
  async function chooseTopic() { try { const result = await api.researches(); setTopics(result.researches || []); } catch (e) { setError(e); } }
  async function associate() { if (!topicId || busy) return; setBusy(true); try { await api.researchReference(topicId, {kind:item.kind,id:item.id}); setStatus("已关联到选题，原资料继续保留"); setTopics(null); } catch (e) { setError(e); } finally {setBusy(false);} }
  return <section className="workspace-reader"><header className="reader-toolbar"><div className="row-actions"><button className="btn btn-sm" onClick={onBack}>← 返回资料列表</button><small>{labels[item.kind]}</small></div><div className="row-actions">{onChoose ? <button className="btn btn-sm" onClick={() => onChoose(item)}>关联这份资料</button> : <button className="btn btn-sm" onClick={chooseTopic}>关联到选题</button>}<button className="btn btn-sm" aria-expanded={ai} onClick={() => ai ? setAi(false) : discuss()}>{ai ? "收起 AI" : "与 AI 讨论"}</button></div></header><ErrorNote error={error} what="阅读资料" /><p className="reader-status" role="status">{status}</p>
  {topics ? <div className="reader-associate"><label>关联到哪个选题？<select aria-label="关联选题" value={topicId} onChange={e => setTopicId(e.target.value)}><option value="">选择选题</option>{topics.map(t => <option key={t.id} value={t.id}>{t.question || t.title}</option>)}</select></label>{!topics.length ? <p>还没有选题，可以先在首页留下一个问题。</p> : null}<button className="btn btn-sm" disabled={!topicId || busy} onClick={associate}>确认关联</button><button className="btn btn-sm" onClick={() => setTopics(null)}>取消</button></div> : null}
  <div className={`reader-columns ${ai ? "with-ai" : ""}`}><article className="reader-document" ref={bodyRef} onScroll={track} onMouseUp={captureSelection} onKeyUp={captureSelection}><small>{item.nature || labels[item.kind]}</small><h1>{item.title}</h1>{/^https?:\/\//i.test(item.sourceUrl || "") ? <a href={item.sourceUrl} target="_blank" rel="noreferrer">打开原始链接 ↗</a> : null}<div className="markdown-body" dangerouslySetInnerHTML={{__html:html}} /><p className="reader-tip">选中原文后，可以围绕这段内容问 AI。</p></article>{mounted ? <aside className="reader-companion" hidden={!ai}><header><strong>围绕原文讨论</strong><button className="btn btn-sm" onClick={() => setAi(false)}>收起</button></header>{selection ? <blockquote>{selection.slice(0, 350)}</blockquote> : null}<AssistantPane embedded emptyMessage="可以问这份资料讲了什么，或选中一段原文一起分析。" scope="reading" surface="rail" scopeId={`reading:${item.kind}:${item.id}`} document={{id:item.id,title:item.title,body:item.body || item.excerpt || ""}} promptRequest={prompt} target={{kind:"none",editable:false,selection:selection ? {text:selection} : null}} /></aside> : null}</div>{selection ? <div className="reader-selection"><span>已选中 {selection.length} 字</span><button className="btn btn-primary btn-sm" onClick={() => discuss(true)}>问 AI</button><button className="btn btn-sm" onClick={() => setSelection("")}>取消选择</button></div> : null}</section>;
}
