import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {openWorkspace} from '../server/storage/workspace.mjs';
import {WORKSPACE_MIGRATIONS,WORKSPACE_SCHEMA_VERSION} from '../server/storage/migrations.mjs';
import {saveIntelligenceProfile,enqueueIntelligence,addIntelligenceSource,intelligenceSource} from '../server/domain/intelligence.mjs';
import {saveIntelligenceBriefs,intelligenceBrief,feedbackIntelligenceBrief,rankIntelligenceBriefs} from '../server/domain/intelligence-feed.mjs';
import {previewIntelligenceTopic,saveIntelligenceTopic,startIntelligenceTopic,intelligenceTopics} from '../server/domain/intelligence-topics.mjs';
import {generateDailyBriefs} from '../server/domain/intelligence-editor.mjs';
import {contentHash,independentEvidenceCount} from '../server/domain/intelligence-quality.mjs';
const root=await fs.mkdtemp(path.join(os.tmpdir(),'xenho-intel-v2-'));let w;
try {
 // Upgrade a real v26 database, keeping IDs, original bytes and old version semantics.
 w=await openWorkspace({xenhoHome:root,migrations:WORKSPACE_MIGRATIONS.filter(m=>m.version<=26)});
 const p=saveIntelligenceProfile(w,{name:'V2 upgrade',query:'Agent',providers:['web'],output:'briefs'}),run=enqueueIntelligence(w,p.id);
 const original='In six runs, two outputs failed the independent check. This small sample does not establish general reliability.';
 w.db.prepare('INSERT INTO intel_sources(id,fingerprint,data_json,created_at) VALUES(?,?,?,?)').run('legacy-source','legacy-fingerprint',JSON.stringify({title:'LLM model experiment',body:original,url:'https://example.com/experiment',provider:'web',readLevel:'original'}),new Date().toISOString());
 w.db.prepare('INSERT INTO intel_run_sources VALUES(?,?)').run(run.id,'legacy-source');
 w.close();w=await openWorkspace({xenhoHome:root});
 assert.equal(w.db.pragma('user_version',{simple:true}),WORKSPACE_SCHEMA_VERSION);
 assert.equal(intelligenceSource(w,'legacy-source').body,original);assert.equal(intelligenceSource(w,'legacy-source').contentHash,contentHash(original));
 const revised=addIntelligenceSource(w,{title:'Correction',body:original+' Correction: this is a pilot.',url:'https://example.com/experiment',provider:'web'},run.id);
 assert.equal(revised.revisionOfId,'legacy-source');const same=addIntelligenceSource(w,{title:revised.title,body:revised.body,url:revised.url,provider:revised.provider},run.id);assert.equal(same.revisionOfId,'legacy-source');assert.equal(intelligenceSource(w,'legacy-source').body,original);
 const post=addIntelligenceSource(w,{title:'Discussion',body:original,url:'https://reddit.com/r/test/comments/abcd/title/',provider:'reddit',contentKind:'post'},run.id);
 const comment=addIntelligenceSource(w,{title:'评论 · Discussion',body:'This is a comment describing one personal observation.',url:post.url,provider:'reddit',contentKind:'comment'},run.id);
 assert.equal(comment.parentItemId,post.id);assert.equal(independentEvidenceCount([comment]),0);assert.equal(independentEvidenceCount([post,comment]),1);
 const ownText='这是我自己的已发表文章，记录了创作中的个人观察与判断，不能被用作外部新信息或者独立验证的证据。';
 const project=w.domain.createProject({title:'自有稿件',confirmed:true,actor:'user'});
 const draft=w.domain.createDraft({projectId:project,bodyMarkdown:ownText,confirmed:true,actor:'user'});
 const own=addIntelligenceSource(w,{title:'回流稿件',body:ownText,url:'https://me.example.com/own',provider:'web'},run.id);
 assert.equal(own.originKind,'internal');assert.equal(own.originRef,`draft:${draft}`);assert.equal(independentEvidenceCount([own]),0);
 const quote='In six runs, two outputs failed the independent check.';
 const make=(patch={})=>({storyKey:'six-runs',title:'一次小规模实验提示需要独立检查',summary:'作者报告小规模实验中发现失败输出。',reason:'检查Agent实际产物',body:'作者报告在小规模实验中发现问题。结果不能推广到所有模型。',confidence:'watch',kind:'practice',evidence:[{sourceId:'legacy-source',quote}],whyItMatters:'完成声明需要产物检查',audienceTakeaway:'为自己的流程增加可执行检查',uncertainties:['小样本不能代表所有模型'],suggestedUses:['设计自己的验收演示'],claims:[{text:'作者报告小规模实验发现失败输出',kind:'author_report',attribution:'实验作者',evidenceIds:['e1'],limitations:['六次运行']}],...patch});
 assert.equal(saveIntelligenceBriefs(w,run.id,[make({evidence:[{sourceId:own.id,quote:ownText}]})]).rejected,1);
 assert.equal(saveIntelligenceBriefs(w,run.id,[make({evidence:[{sourceId:comment.id,quote:comment.body}]})]).rejected,1);
 const review=[{index:0,verdict:'supported',claims:[{id:'c1',verdict:'supported'}]}];
 const pending=saveIntelligenceBriefs(w,run.id,[make({storyKey:'pending'})]).saved[0];assert.equal(pending.editorialState,'needs_review');
 const inflated=saveIntelligenceBriefs(w,run.id,[make({storyKey:'inflated',summary:'1000次实验表明所有模型都可靠'})],[],null,review).saved[0];assert.equal(inflated.editorialState,'needs_review');assert.ok(inflated.quality.reasons.some(r=>r.includes('数字')));
 const upgraded=saveIntelligenceBriefs(w,run.id,[make({storyKey:'pending'})],[],null,review).saved[0];assert.equal(upgraded.id,pending.id);assert.equal(upgraded.version,2);assert.equal(upgraded.editorialState,'ready');
 const ready=saveIntelligenceBriefs(w,run.id,[make()],[],null,review).saved[0];assert.equal(ready.editorialState,'ready');assert.ok(ready.clusterId);assert.equal(ready.evidence[0].quoteCheck,'matched');assert.equal(ready.evidence[0].scopeCheck,'ai_reviewed');
 assert.equal(w.db.prepare('SELECT count(*) n FROM intel_cluster_members WHERE cluster_id=?').get(ready.clusterId).n,1);
 feedbackIntelligenceBrief(w,ready.id,{dismissed:true,reason:'weak_evidence'});assert.equal(w.db.prepare('SELECT reason FROM intel_feedback WHERE brief_id=?').get(ready.id).reason,'weak_evidence');
 assert.throws(()=>feedbackIntelligenceBrief(w,ready.id,{dismissed:true,reason:'made_up'}));
 const candidate={workingTitle:'为内容Agent增加产物检查',audience:'个人创作者',angle:'用可复现检查验证完成状态',deliverable:'小型演示和清单',whyNow:'已有实验暴露验收缺口',evidenceGaps:['需在自己的工作流中复测'],researchTasks:['设计三个检查并记录结果'],nonClaims:['不能声称适用于所有模型'],evidence:[{sourceId:'legacy-source',quote}]};
 const before=w.db.prepare('SELECT count(*) n FROM intel_cards').get().n;
 const preview=await previewIntelligenceTopic(w,{}, {briefIds:[ready.id]},{completeJson:async()=>({data:{candidate}})});
 assert.equal(w.db.prepare('SELECT count(*) n FROM intel_cards').get().n,before);assert.equal(preview.readiness,'needs_evidence');
 assert.throws(()=>saveIntelligenceTopic(w,{candidate:preview}),/确认/);
 assert.throws(()=>saveIntelligenceTopic(w,{confirmed:true,candidate:{...preview,sourceHashes:{}}}),/版本/);
 assert.throws(()=>saveIntelligenceTopic(w,{confirmed:true,candidate:{...preview,evidence:[{sourceId:'legacy-source',quote:'This quote is fabricated.'}]}}),/校验/);
 assert.throws(()=>saveIntelligenceTopic(w,{confirmed:true,candidate:{...preview,angle:'我去年采访过一个朋友，发现他靠这个方法赚到了很多钱。'}}),/个人经历|叙事/);
 const saved=saveIntelligenceTopic(w,{confirmed:true,candidate:preview});assert.equal(saveIntelligenceTopic(w,{confirmed:true,candidate:preview}).id,saved.id);assert.equal(intelligenceTopics(w).opportunities.find(o=>o.id===saved.id).readiness,'needs_evidence');
 assert.throws(()=>startIntelligenceTopic(w,saved.id,{}),/确认/);
 const research=startIntelligenceTopic(w,saved.id,{confirmed:true});assert.equal(startIntelligenceTopic(w,saved.id,{confirmed:true}).id,research.id);assert.ok(research.notes.includes(candidate.nonClaims[0]));assert.ok(research.openQuestions.includes(candidate.researchTasks[0]));assert.ok(research.references.length);assert.deepEqual(intelligenceBrief(w,ready.id).researchIds,[research.id]);
 const oldPreview=await previewIntelligenceTopic(w,{}, {briefIds:[upgraded.id]},{completeJson:async()=>({data:{candidate}})});
 const oldTopic=saveIntelligenceTopic(w,{confirmed:true,candidate:oldPreview});
 w.db.prepare('UPDATE intel_briefs SET version=version+1 WHERE id=?').run(upgraded.id);
 assert.throws(()=>startIntelligenceTopic(w,oldTopic.id,{confirmed:true}),/重新预览/);
 const newPreview=await previewIntelligenceTopic(w,{}, {briefIds:[upgraded.id]},{completeJson:async()=>({data:{candidate}})});
 const newTopic=saveIntelligenceTopic(w,{confirmed:true,candidate:newPreview});
 assert.notEqual(newTopic.id,oldTopic.id,'新版本依据不能被旧选题去重吞掉');
 assert.equal(newTopic.briefVersions[upgraded.id],upgraded.version+1);
 const calls=[];
 const edited=await generateDailyBriefs(w,{},run,[intelligenceSource(w,'legacy-source')],[],{completeJson:async(_env,input)=>{const d=JSON.parse(input.user);calls.push(d.step);if(d.step==='organize')return {data:{groups:[{key:'review-pipeline',focus:'小规模实验',connection:'单篇报告',relationship:'standalone',sourceIds:['legacy-source']}]}};if(d.step==='scope-review')return {data:{reviews:review},usage:{total_tokens:20},model:'test'};return {data:{briefs:[make({groupKey:'review-pipeline'})]},usage:{total_tokens:50},model:'test'};}});
 assert.equal(edited.saved[0].editorialState,'ready');assert.deepEqual(calls,['organize','compose','scope-review']);
 assert.equal(w.db.prepare("SELECT json_extract(state_json,'$.usage.total_tokens') n FROM intel_steps WHERE run_id=? AND provider='scope-review'").get(run.id).n,20);
 assert.deepEqual(w.db.pragma('foreign_key_check'),[]);
 const ranked=Array.from({length:12},(_,i)=>({id:'rank'+i,editorialState:'ready',editionDate:'today',clusterId:'cluster'+Math.floor(i/2),sourceMeta:[{originKind:'external',publisherKey:i<8?'one':'other'}],updatedAt:'today'}));assert.equal(rankIntelligenceBriefs(ranked,'today').length,4,'同主题一条且同发布主体最多两条');
 const id=ready.id;w.close();w=await openWorkspace({xenhoHome:root});assert.equal(intelligenceBrief(w,id).editorialState,'ready');assert.equal(intelligenceTopics(w).opportunities.find(o=>o.id===saved.id).readiness,'in_progress');
 console.log('intelligence-v2: migration, identity, immutable revisions, comments, claim scope, feedback, preview, confirmation, stale evidence, research idempotency and pipeline passed');
} finally {w?.close();assert(path.relative(os.tmpdir(),root)&&!path.relative(os.tmpdir(),root).startsWith('..'));await fs.rm(root,{recursive:true,force:true});}
