import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {openWorkspace} from '../server/storage/workspace.mjs';
import {addIntelligenceSource,saveIntelligenceProfile,enqueueIntelligence,updateRun} from '../server/domain/intelligence.mjs';
import {executeIntelligence} from '../server/domain/intelligence-runner.mjs';
import {intelligenceFeed,feedbackIntelligenceBrief,saveIntelligenceBriefs,intelligenceBrief,refreshIntelligenceFeed} from '../server/domain/intelligence-feed.mjs';
import {unifiedSummary,reconcileUnifiedSources,mergeBriefIdentities,canonicalBriefId,executeUnifiedBriefs} from '../server/domain/intelligence-unified.mjs';
import {persistIntelligenceCluster} from '../server/domain/intelligence-quality.mjs';
import {reviewAction} from '../server/acquisition/review.mjs';
const root=await fs.mkdtemp(path.join(os.tmpdir(),'xenho-unified-'));let w;
try {
 w=await openWorkspace({xenhoHome:root});
 // Supports running before the registry lands; all operations remain in this isolated database.
 w.db.exec(await fs.readFile(new URL('../server/storage/migrations/0033-intelligence-unified.sql',import.meta.url),'utf8'));
 const profile=saveIntelligenceProfile(w,{name:'测试情报',query:'AI',providers:['collected'],output:'briefs'});
 const quote='The language model experiment used a limited sample and requires independent verification.';
 const sources=Array.from({length:11},(_,i)=>addIntelligenceSource(w,{title:`LLM experiment ${i}`,url:`https://publisher${i}.example/report`,body:`${quote} Report identity ${i}.`,provider:'web',readLevel:'original'}));
 const blocked=addIntelligenceSource(w,{title:'LLM private content',url:'https://private.example/report',body:quote+' private text',provider:'web',readLevel:'original'});
 w.db.prepare("UPDATE intel_sources SET acquisition_identity='private-test',rights_json='{}' WHERE id=?").run(blocked.id);
 let modelCalls=0;const inspected=[];
 const deps={completeJson:async(_env,input)=>{modelCalls++;const d=JSON.parse(input.user);
  if(d.material){assert.ok(!d.material.includes('private text'));inspected.push(d.material);return {data:{relevance:'ai_relevant',reason:'原文讨论模型实验',evidence:[quote],title:'模型实验提供有限样本的观察',guideClaims:[{text:'作者说明实验有范围限制',quotes:[quote]}],topic:'模型实验',uncertainties:['需要独立验证']}};}
  if(d.step==='organize')return {data:{groups:d.sources.map(s=>({key:`experiment:${s.id}`,focus:s.title,connection:'单篇实验报告',relationship:'standalone',sourceIds:[s.id]}))}};
  if(d.step==='scope-review')return {data:{reviews:d.candidates.map(c=>({index:c.index,verdict:'supported',claims:[{id:'c1',verdict:'supported'}]}))}};
  if(d.step==='compose')return {data:{briefs:d.groups.map(g=>({groupKey:g.key,storyKey:g.key,title:'模型实验需要独立检查',summary:'作者报告有限样本的实验，需要独立验证。',reason:'帮助判断模型输出',body:'作者报告实验采用有限样本，仍需独立验证。',confidence:'reliable',kind:'practice',evidence:[{sourceId:g.sourceIds[0],quote}],wiki:[],whyItMatters:'模型输出需要验证',audienceTakeaway:'核对实际产物',uncertainties:['有限样本'],suggestedUses:['设计自己的检查'],claims:[{text:'作者称实验需要独立验证',kind:'author_report',attribution:'实验作者',evidenceIds:['e1'],limitations:['有限样本']}]}))}};
  throw Error('unexpected model task');
 }};
 const run=enqueueIntelligence(w,profile.id);
 let result=await executeIntelligence(w,{}, {runId:run.id},deps);
 assert.equal(result.status,'queued','first batch schedules continuation');
 assert.equal(intelligenceFeed(w).briefs.length,8);
 result=await executeIntelligence(w,{}, {runId:run.id},deps);
 assert.equal(result.status,'done');assert.equal(intelligenceFeed(w).briefs.length,11);assert.equal(unifiedSummary(w).permissionRequired,1);
 assert.equal(intelligenceFeed(w).recommendationIds.length,11,'full recommendation set is not limited to eight');
 const selected=intelligenceFeed(w).briefs[0];feedbackIntelligenceBrief(w,selected.id,{saved:true,dismissed:true});
 const count=modelCalls;const second=enqueueIntelligence(w,profile.id);await executeIntelligence(w,{}, {runId:second.id},deps);
 assert.equal(modelCalls,count,'unchanged materials do not consume model calls');assert.equal(intelligenceFeed(w).briefs.length,11);assert.equal(intelligenceFeed(w).briefs.find(b=>b.id===selected.id).saved,true);assert.equal(intelligenceFeed(w).briefs.find(b=>b.id===selected.id).dismissed,true);
 // A fresh source advances despite a preceding permanent model failure; retries are finite.
 const failing=addIntelligenceSource(w,{title:'LLM failing source',url:'https://failed.example/report',body:quote+' failure fixture',provider:'web',readLevel:'original'});
 const third=enqueueIntelligence(w,profile.id);let attempts=0;const failDeps={completeJson:async()=>{attempts++;throw Error('model unavailable');}};
 await executeIntelligence(w,{}, {runId:third.id},failDeps);await executeIntelligence(w,{}, {runId:third.id},failDeps);
 assert.equal(attempts,2);assert.equal(unifiedSummary(w).failures,1);assert.equal(intelligenceFeed(w).briefs.length,11);
 w.db.exec(await fs.readFile(new URL('../server/storage/migrations/0035-intelligence-aliases.sql',import.meta.url),'utf8'));
 const canonical=intelligenceFeed(w).briefs[1].id;const originalCount=w.db.prepare('SELECT count(*) n FROM intel_briefs').get().n;
 mergeBriefIdentities(w,canonical,[selected.id]);assert.equal(canonicalBriefId(w,selected.id),canonical);assert.equal(intelligenceBrief(w,selected.id).id,canonical);assert.equal(intelligenceBrief(w,canonical).saved,true);assert.equal(intelligenceBrief(w,canonical).dismissed,true);assert.equal(intelligenceFeed(w).briefs.length,10);assert.equal(w.db.prepare('SELECT count(*) n FROM intel_briefs').get().n,originalCount,'historical rows remain intact');feedbackIntelligenceBrief(w,selected.id,{dismissed:false});assert.equal(intelligenceBrief(w,canonical).dismissed,false);
 // A manual split must survive regeneration, including the selected side and user state.
 const splitSources=[sources[3],sources[4]],briefsBefore=intelligenceFeed(w).briefs;
 const original=briefsBefore.find(b=>b.evidence.some(e=>e.sourceId===splitSources[0].id));
 const merged=briefsBefore.find(b=>b.evidence.some(e=>e.sourceId===splitSources[1].id));
 const fixtureData=JSON.parse(w.db.prepare('SELECT data_json FROM intel_briefs WHERE id=?').get(original.id).data_json);
 fixtureData.evidence=splitSources.map(s=>({sourceId:s.id,quote}));w.db.prepare('UPDATE intel_briefs SET data_json=? WHERE id=?').run(JSON.stringify(fixtureData),original.id);
 mergeBriefIdentities(w,original.id,[merged.id]);feedbackIntelligenceBrief(w,original.id,{saved:true});
 const cluster=persistIntelligenceCluster(w,{key:'test:manual-split',focus:'LLM grouped experiments',relationship:'complementary'},splitSources);
 w.db.prepare('INSERT OR REPLACE INTO acquisition_cluster_reviews(cluster_id,status,manual,data_json,updated_at) VALUES(?,?,?,?,?)').run(cluster,'unreviewed',0,'{}',new Date().toISOString());
 for(const source of splitSources)w.db.prepare('INSERT OR REPLACE INTO acquisition_review_members(source_id,cluster_id) VALUES(?,?)').run(source.id,cluster);
 const split=reviewAction(w,cluster,{confirmed:true,action:'split',sourceIds:[splitSources[0].id]});assert(split.splitClusterId);
 assert.equal(w.db.prepare('SELECT status FROM intel_unified_sources WHERE source_id=?').get(splitSources[0].id).status,'pending');
 const splitRun=enqueueIntelligence(w,profile.id);await executeIntelligence(w,{}, {runId:splitRun.id},deps);
 const splitCards=intelligenceFeed(w).briefs.filter(b=>b.evidence.some(e=>splitSources.some(s=>s.id===e.sourceId)));
 assert.equal(splitCards.length,2,'split yields two independently readable cards');
 assert(splitCards.every(b=>b.evidence.length===1),'split does not append old grouped evidence back');
 assert.equal(intelligenceBrief(w,original.id).saved,true,'original card state survives correction');
 const callCount=modelCalls;const stableRun=enqueueIntelligence(w,profile.id);await executeIntelligence(w,{}, {runId:stableRun.id},deps);assert.equal(modelCalls,callCount);
 reviewAction(w,split.splitClusterId,{confirmed:true,action:'merge',targetId:cluster});
 const mergeRun=enqueueIntelligence(w,profile.id);await executeIntelligence(w,{}, {runId:mergeRun.id},{completeJson:async(env,input)=>{const result=await deps.completeJson(env,input),d=JSON.parse(input.user);if(d.step==='compose')for(const brief of result.data.briefs)brief.evidence=d.groups.find(g=>g.key===brief.groupKey).sourceIds.map(sourceId=>({sourceId,quote}));return result;}});
 const mergedCards=intelligenceFeed(w).briefs.filter(b=>b.evidence.some(e=>splitSources.some(s=>s.id===e.sourceId)));
 assert.equal(mergedCards.length,1,'explicit manual merge restores one canonical card');assert.equal(mergedCards[0].evidence.length,2);assert.equal(mergedCards[0].saved,true);
 w.db.prepare("UPDATE intel_unified_sources SET status='processing',attempts=1 WHERE source_id=?").run(sources[7].id);
 w.db.prepare("UPDATE intel_unified_sources SET status='processing',attempts=2 WHERE source_id=?").run(sources[6].id);
 const interruptedRun=enqueueIntelligence(w,profile.id);await executeIntelligence(w,{}, {runId:interruptedRun.id},deps);
 assert.equal(w.db.prepare('SELECT status FROM intel_unified_sources WHERE source_id=?').get(sources[7].id).status,'done','interrupted composition resumes');
 assert.equal(w.db.prepare('SELECT status FROM intel_unified_sources WHERE source_id=?').get(sources[6].id).status,'failed','interrupted retries remain bounded');
 refreshIntelligenceFeed(w,{collect:false});
 assert.deepEqual(w.db.prepare('SELECT status,attempts FROM intel_unified_sources WHERE source_id=?').get(failing.id),{status:'failed',attempts:2},'automatic refresh cannot reset exhausted retries');
 const manualRefresh=refreshIntelligenceFeed(w,{collect:true});
 assert.deepEqual(w.db.prepare('SELECT status,attempts FROM intel_unified_sources WHERE source_id=?').get(failing.id),{status:'pending',attempts:0},'explicit user update permits a fresh bounded retry');
 await executeUnifiedBriefs(w,{},manualRefresh.id,deps);
 assert.equal(w.db.prepare('SELECT status FROM intel_unified_sources WHERE source_id=?').get(failing.id).status,'done','recovered model can process a previously exhausted source');
 assert.deepEqual(w.db.pragma('foreign_key_check'),[]);
 console.log('intelligence-unified: 11-item continuation, permission isolation, stable states, manual split, interrupted recovery, cache, bounded retry and manual recovery passed');
} finally {w?.close();assert(!path.relative(os.tmpdir(),root).startsWith('..'));await fs.rm(root,{recursive:true,force:true});}
