import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { Readable } from 'node:stream';
import { openWorkspace } from '../server/storage/workspace.mjs';
import { intelligenceRoutes } from '../server/routes/intelligence.mjs';
import { saveIntelligenceProfile as profile, enqueueIntelligence as enqueue, intelligenceRun as run, intelligenceOverview as overview, retryIntelligence as retry, cancelIntelligence as cancel, scheduleIntelligence as schedule, addIntelligenceSource as source, runSources, saveIntelligenceCards as cards, adoptIntelligenceCard as adopt, setIntelligenceCard as setCard, stepState } from '../server/domain/intelligence.mjs';
import { executeIntelligence as executeRaw } from '../server/domain/intelligence-runner.mjs';
const execute=(w,e,p,d={})=>executeRaw(w,e,p,{planResearch:async()=>({}),...d});
const root=await fs.mkdtemp(path.join(os.tmpdir(),'xenho-intelligence-'));
let w;
const base={name:'AI 创作问题',query:'AI',providers:['local'],frequency:'manual',limit:5};
const original='真实测试原文：AI 工具需要保留上下文和反馈，不能只看模型评分。这是完整的本地测试资料，不代表外部事实。';
const emptyModel=async()=>({data:{cards:[]}});
const candidate=(s,question='为什么工具需要反馈？')=>({question,audience:'独立创作者',why:'观察到一个待研究的问题',angle:'比较上下文与模型表现',gaps:'还需要真实案例',evidence:[{sourceId:s.id,quote:'AI 工具需要保留上下文和反馈'}],wiki:[{id:'invented-wiki',reason:'应被过滤'}]});
async function call(method,url,params={},body){let status,data;await intelligenceRoutes.find(r=>r.method===method&&r.path===url).handler({workspace:w,env:{},params,req:Readable.from(body===undefined?[]:[Buffer.from(JSON.stringify(body))]),res:{writeHead(s){status=s;},end(s){data=JSON.parse(s);}}});return {status,...data};}
try{
 w=await openWorkspace({xenhoHome:path.join(root,'Xenho')});
 const p=profile(w,base);
 assert.equal(p.nextDueAt,null);
 for(const patch of [{name:''},{limit:0},{limit:21},{limit:2.5},{frequency:'hourly'},{enabled:'yes'},{providers:['douyin-hot']},{providers:['xiaohongshu-hot']},{providers:[]},{providers:['reddit'],subreddits:['../escape'],paidApproved:true}]) assert.throws(()=>profile(w,{...base,...patch}),e=>e.status===400,JSON.stringify(patch));
 assert.equal((await call('POST','/api/workspace/intelligence/profiles',{}, {...base,providers:['hot']})).status,400);
 const daily=profile(w,{...base,name:'日度',frequency:'daily'}),weekly=profile(w,{...base,name:'周度',frequency:'weekly'});
 const current=Date.now();
 assert.ok(Math.abs(Date.parse(daily.nextDueAt)-current-86400000)<2000);
 assert.ok(Math.abs(Date.parse(weekly.nextDueAt)-current-604800000)<2000);
 assert.equal(profile(w,{...daily,name:'改名'}).nextDueAt,daily.nextDueAt,'ordinary edits preserve schedule');
 const disabled=profile(w,{...base,name:'关闭',frequency:'daily',enabled:false});assert.equal(disabled.nextDueAt,null);
 assert.deepEqual(schedule(w,{now:new Date(current)}),[]);
 const dueAt=new Date(current+8*86400000),scheduled=schedule(w,{now:dueAt});assert.equal(scheduled.length,2);assert.deepEqual(schedule(w,{now:dueAt}),[]);
 const nextProfiles=overview(w).profiles;
 assert.equal(Date.parse(nextProfiles.find(x=>x.id===daily.id).nextDueAt),+dueAt+86400000);
 assert.equal(Date.parse(nextProfiles.find(x=>x.id===weekly.id).nextDueAt),+dueAt+604800000);
 let r=enqueue(w,p.id);assert.equal(enqueue(w,p.id).id,r.id,'active enqueue is idempotent');
 const a=source(w,{title:'记录',body:original,url:'https://example.com/ai',provider:'local'},r.id);
 assert.equal(source(w,{title:'记录改名',body:original,url:'https://example.com/ai',provider:'local'},r.id).id,a.id);
 assert.equal(runSources(w,r.id).length,1);
 const summary=source(w,{title:'搜索摘要',body:original,url:'https://example.com/snippet',provider:'web',readLevel:'snippet'},r.id);
 assert.equal(cards(w,r.id,[{...candidate(a),evidence:[{sourceId:a.id,quote:'AI 工具一定可以提高所有人的效率'}]},candidate(summary)],[]).rejected,2,'invented quotes and search snippets never become evidence');
 assert.equal(overview(w).cards.length,0);
 await execute(w,{}, {runId:r.id},{collect:async()=>[{title:'记录',body:original,url:'https://example.com/ai',provider:'local'}],completeJson:async(_env,request)=>{const input=JSON.parse(request.user);assert.ok(input.sources.some(s=>s.id===a.id));return {data:{cards:[candidate(a)]}};}});
 assert.equal(run(w,r.id).status,'done');
 let card=overview(w).cards[0];assert.deepEqual(card.wiki,[]);assert.equal(runSources(w,r.id).length,2);
 const adopted=adopt(w,card.id);assert.equal(adopt(w,card.id).id,adopted.id);assert.equal(adopted.references.length,1);
 const capture=w.db.prepare('SELECT * FROM captures WHERE id=?').get(adopted.references[0].id);
 assert.ok(capture,'adoption links a persisted capture');
 assert.throws(()=>setCard(w,card.id,'dismissed'),e=>e.status===409);
 const captureCount=w.db.prepare('SELECT count(*) n FROM captures').get().n;adopt(w,card.id);assert.equal(w.db.prepare('SELECT count(*) n FROM captures').get().n,captureCount);
 const again=enqueue(w,p.id);assert.notEqual(again.id,r.id);source(w,{title:'记录',body:original,url:'https://example.com/ai',provider:'local'},again.id);
 cards(w,again.id,[candidate(a)],[]);assert.equal(overview(w).cards.length,1);assert.equal(overview(w).cards[0].researchId,adopted.id);
 cancel(w,again.id);let collected=false;await execute(w,{}, {runId:again.id},{collect:async()=>{collected=true;return[];}});assert.equal(collected,false);assert.equal(run(w,again.id).status,'cancelled');
 retry(w,again.id);assert.equal(run(w,again.id).status,'queued');
 await execute(w,{}, {runId:again.id},{collect:async()=>{cancel(w,again.id);return[{title:'late',body:'取消之后不允许保存这份测试资料'}];},completeJson:emptyModel});assert.equal(run(w,again.id).status,'cancelled');assert.ok(!runSources(w,again.id).some(s=>s.title==='late'));
 const wp=profile(w,{...base,providers:['web']}),wr=enqueue(w,wp.id);let searches=0,reads=[];
 const webDeps={searchWeb:async()=>{searches++;return {sources:[{url:'https://example.com/good',title:'AI good'},{url:'https://example.com/retry',title:'AI retry'}]};},readArticle:async(url)=>{reads.push(url);if(url.endsWith('/retry'))throw new Error('temporary read failure');return {title:'Good',url,markdown:original};},completeJson:emptyModel};
 await execute(w,{}, {runId:wr.id},webDeps);assert.equal(run(w,wr.id).status,'partial');assert.equal(runSources(w,wr.id).length,1);
 retry(w,wr.id);await execute(w,{}, {runId:wr.id},{...webDeps,readArticle:async(url)=>{reads.push(url);return {title:'Retry',url,markdown:original};}});
 assert.equal(run(w,wr.id).status,'done');assert.equal(searches,1,'retry reuses persisted search result');assert.equal(reads.filter(u=>u.endsWith('/good')).length,1,'completed pages are not fetched twice');assert.equal(runSources(w,wr.id).length,2);
 const ap=profile(w,{...base,providers:['aihot']}),ar=enqueue(w,ap.id);let aiReads=[];
 await execute(w,{}, {runId:ar.id},{fetchAiHot:async()=>({ok:true,items:[{title:'AI 上下文',summary:'AI',link:'https://example.com/industry'},{title:'无关娱乐新闻',summary:'娱乐',link:'https://example.com/unrelated'}]}),readArticle:async(url)=>{aiReads.push(url);return {title:'AI',url,markdown:original};},completeJson:emptyModel});assert.deepEqual(aiReads,['https://example.com/industry']);assert.equal(run(w,ar.id).status,'done');
 const xp=profile(w,{...base,providers:['x'],accounts:['OpenAI'],paidApproved:true}),xr=enqueue(w,xp.id);let triggers=0;
 const brightDeps={trigger:async()=>{triggers++;return 's_resume';},progress:async()=>{throw new Error('temporary progress failure fake-test-key');},download:async()=>[{url:'https://x.com/OpenAI/status/1',description:original,date_posted:new Date().toISOString()}],completeJson:emptyModel};
 await execute(w,{BRIGHTDATA_API_KEY:'fake-test-key'},{runId:xr.id},brightDeps);assert.equal(run(w,xr.id).status,'failed');assert.equal(stepState(w,xr.id,'x').snapshotId,'s_resume');assert.ok(!JSON.stringify(run(w,xr.id)).includes('fake-test-key'),'provider errors cannot expose configured keys');assert.throws(()=>retry(w,xr.id,{snapshotIds:{x:'s_replace'}}),e=>e.status===400||e.status===409,'known snapshots cannot be silently replaced');
 w.close();w=await openWorkspace({xenhoHome:path.join(root,'Xenho')});
 retry(w,xr.id);await execute(w,{BRIGHTDATA_API_KEY:'fake-test-key'},{runId:xr.id},{...brightDeps,progress:async()=> 'ready'});assert.equal(triggers,1,'restart/retry never repeats an existing paid snapshot');assert.equal(run(w,xr.id).status,'done');
 const uncertain=enqueue(w,xp.id);const uncertainDeps={...brightDeps,trigger:async()=>{triggers++;throw new Error('trigger connection lost');},progress:async()=> 'ready'};
 await execute(w,{BRIGHTDATA_API_KEY:'fake-test-key'},{runId:uncertain.id},uncertainDeps);assert.equal(stepState(w,uncertain.id,'x').uncertain,true);
 retry(w,uncertain.id);await execute(w,{BRIGHTDATA_API_KEY:'fake-test-key'},{runId:uncertain.id},uncertainDeps);assert.equal(triggers,2,'uncertain external trigger cannot be silently charged again');assert.match(run(w,uncertain.id).coverage.find(s=>s.provider==='x').error,/snapshot ID/);
 assert.throws(()=>retry(w,uncertain.id,{snapshotIds:{x:'bad/id'}}),e=>e.status===400);
 retry(w,uncertain.id,{snapshotIds:{x:'s_recovered'}});await execute(w,{BRIGHTDATA_API_KEY:'fake-test-key'},{runId:uncertain.id},{...brightDeps,progress:async()=> 'ready'});assert.equal(triggers,2);assert.equal(run(w,uncertain.id).status,'done');
 const rp=profile(w,{...base,providers:['reddit'],subreddits:['LocalLLaMA'],paidApproved:true}),rr=enqueue(w,rp.id);
 await execute(w,{BRIGHTDATA_API_KEY:'fake-test-key'},{runId:rr.id},{trigger:async(_key,_dataset,input,options)=>{assert.equal(input[0].url,'https://www.reddit.com/r/localllama/');assert.equal(options.limitPerInput,5);return 's_reddit';},progress:async()=> 'ready',download:async()=>[{url:'https://reddit.com/r/LocalLLaMA/comments/test',selftext:original,comments:[{body:'这是来自真实采集结构的一条测试评论',user_commenting:'human'},{body:'这条机器评论不应该成为参考来源',user_commenting:'AutoModerator'}]}],completeJson:emptyModel});assert.equal(run(w,rr.id).status,'done');assert.equal(runSources(w,rr.id).length,2);
 const simple=profile(w,{name:'GPT模型进展和使用',query:'无'});
 assert.equal(simple.query,'GPT模型进展和使用','empty placeholder cannot replace actual topic');
 assert.ok(simple.providers.includes('reddit')&&simple.providers.includes('x'));
 const sr=enqueue(w,simple.id);const queryLog=[];
 await execute(w,{}, {runId:sr.id},{planResearch:async p=>{assert.equal(p.query,'GPT模型进展和使用');return {query:'GPT OpenAI model updates'};},collect:async provider=>provider==='web'?[{title:'法院资料',body:'这是一篇无关法院诉讼文书，不能作为GPT模型进展的调研资料。',url:'https://example.com/court'},{title:'GPT更新',body:'GPT models support new tools and instruction following capabilities.',url:'https://example.com/gpt'}]:[],completeJson:async(_env,request)=>{const data=JSON.parse(request.user);return {data:{relevantSources:data.sources.filter(x=>x.title==='GPT更新').map(x=>({sourceId:x.id,reason:'GPT模型能力更新'})),cards:[]}};}});
 assert.ok(!overview(w).sources.some(s=>s.title==='法院资料'),'unrelated fetched pages never enter visible collection');
 const approved=overview(w).sources.find(s=>s.title==='GPT更新');assert.equal(approved.profileName,simple.name);assert.equal(approved.runId,sr.id);
 assert.ok(!overview(w).sources.some(s=>s.title==='搜索摘要'),'unscreened historical data stays out of current collection');
 const full=await call('GET','/api/workspace/intelligence/sources/:id',{id:approved.id});assert.equal(full.source.title,'GPT更新');
 const api=await call('GET','/api/workspace/intelligence');assert.equal(api.status,200);assert.ok(api.profiles.length>=7);assert.equal(api.capabilities.x,false);
 console.log('intelligence: profile validation, schedules, evidence, adoption, cancellation, retry, page resume, snapshot recovery and API passed');
}finally{w?.close();await fs.rm(root,{recursive:true,force:true});}
