import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import { openWorkspace } from '../server/storage/workspace.mjs';
import { createApi } from '../server/api.mjs';
import { projectCreativeContext } from '../server/domain/content-project.mjs';
import { assertGroundedGeneratedText } from '../server/domain/integrity.mjs';
const root=await fs.mkdtemp(path.join(os.tmpdir(),'xenho-personal-assets-'));
let w,server;let request=null;let modelResult;const narrative='我去年开始创业，花了三个月开发写作工作台。';
try{
 w=await openWorkspace({xenhoHome:root});
 const api=createApi({AGENT_LLM_BASE_URL:'https://ai.example.test/v1',NOTE_COMPLETE_JSON:async(_env,input)=>{request=input;if(modelResult instanceof Error)throw modelResult;return modelResult;}},{workspace:Promise.resolve(w)});
 server=http.createServer((req,res)=>api(req,res,()=>{res.writeHead(404);res.end();}));await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const base=`http://127.0.0.1:${server.address().port}/api/workspace`;
 const call=async(url,body,method=body?'POST':'GET')=>{if(method==='POST'&&/\/projects\/.*\/personal-assets$/.test(url)&&body?.confirmed)body={...body,destinations:['https://ai.example.test/v1']};const res=await fetch(base+url,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:res.status,...await res.json()};};
 let note=(await call('/quick-notes',{text:narrative+' #经历',tags:['创业']})).item;
 assert(note.id);assert.equal(note.version,1);assert.deepEqual(note.tags,['创业','经历']);
 assert.equal((await call('/quick-notes?tag=创业')).items.length,1);
 assert.equal((await call('/quick-notes?q=找不到')).items.length,0);
 assert.equal((await call(`/quick-notes/${note.id}`,{text:'changed',expectedVersion:0},'PUT')).status,409);
 note=(await call(`/quick-notes/${note.id}`,{pinned:true,sourceUrl:'https://example.com/note',expectedVersion:1},'PUT')).item;assert.equal(note.pinned,true);assert.equal(note.sourceUrl,'https://example.com/note');
 assert.equal((await call(`/quick-notes/${note.id}`,{sourceUrl:'javascript:alert(1)',expectedVersion:note.version},'PUT')).status,400);
 const before=w.db.prepare('SELECT count(*) n FROM personal_assets').get().n;
 modelResult={summary:'记录了一次创业经历',questions:['你最想保留什么？'],assetCandidate:{kind:'experience',title:'我的创业经历',body:narrative}};
 const insight=await call(`/quick-notes/${note.id}/insights`,{refresh:true});assert.equal(insight.status,200);assert(request.user.includes(narrative));assert.equal(w.db.prepare('SELECT count(*) n FROM personal_assets').get().n,before);
 modelResult={model:'mock-model',data:{summary:'包装返回也能读取',questions:['接下来准备怎么做？'],assetCandidate:null},usage:null};
 const wrappedInsight=await call(`/quick-notes/${note.id}/insights`,{refresh:true});assert.equal(wrappedInsight.status,200);assert.equal(wrappedInsight.insight.summary,'包装返回也能读取');
 assert.equal((await call('/personal-assets',insight.insight.assetCandidate)).status,400);
 assert.equal((await call('/personal-assets',{...insight.insight.assetCandidate,body:'我去年拿到一百万',confirmed:true})).status,400);
 let asset=(await call('/personal-assets',{...insight.insight.assetCandidate,confirmed:true})).item;assert(asset.id);assert.equal(asset.usage,'ask');
 const privateAsset=(await call('/personal-assets',{kind:'identity',title:'不公开身份',body:'PRIVATE_SECRET_481',usage:'private',confirmed:true})).item;
 assert(!(await call('/library?q=PRIVATE_SECRET_481')).items.length);
 const project=w.domain.createProject({title:'我的创作',actor:'user',confirmed:true});const other=w.domain.createProject({title:'另一篇',actor:'user',confirmed:true});
 const url=`/projects/${project}/personal-assets`;
 assert(!(await call(url)).items.some(x=>x.id===privateAsset.id));
 assert.equal((await call(url,{assetId:privateAsset.id,expectedVersion:1,confirmed:true})).status,400);
 assert.equal((await call(url,{assetId:asset.id,expectedVersion:asset.version})).status,400);
 assert.equal(projectCreativeContext(w,project).experiences.length,0);
 assert.equal((await call(url,{assetId:asset.id,expectedVersion:asset.version,confirmed:true})).references.length,1);
 assert.equal(projectCreativeContext(w,project).experiences.length,1);assert.equal(projectCreativeContext(w,other).experiences.length,0);
 assertGroundedGeneratedText(narrative,w.domain.groundingMaterials(project));assert.throws(()=>assertGroundedGeneratedText(narrative,w.domain.groundingMaterials(other)));
 asset=(await call(`/personal-assets/${asset.id}`,{title:'更新标题',expectedVersion:asset.version,confirmed:true},'PUT')).item;
 assert.equal((await call(url)).references.length,0);assert.equal((await call(`/personal-assets/${asset.id}`)).versions.length,2);
 assert.equal((await call(url,{assetId:asset.id,expectedVersion:1,confirmed:true})).status,409);
 await call(url,{assetId:asset.id,expectedVersion:asset.version,confirmed:true});
 asset=(await call(`/personal-assets/${asset.id}`,{usage:'private',expectedVersion:asset.version,confirmed:true},'PUT')).item;
 assert.equal((await call(url)).references.length,0);assert.equal(projectCreativeContext(w,project).experiences.length,0);
 assert.equal((await call(url,{assetId:asset.id},'DELETE')).status,400);
 assert.equal((await call(url,{assetId:asset.id,confirmed:true},'DELETE')).status,200);
 modelResult={summary:'伪造候选',questions:[],assetCandidate:{kind:'experience',title:'假的',body:'从来没有说过的事'}};
 assert.equal((await call(`/quick-notes/${note.id}/insights`,{refresh:true})).status,502);
 modelResult=new Error('模拟模型不可用');assert.equal((await call(`/quick-notes/${note.id}/insights`,{refresh:true})).ok,false);
 await call(`/quick-notes/${note.id}/trash`,{});assert.equal((await call('/quick-notes')).items.length,0);assert.equal((await call(`/personal-assets/${asset.id}`)).item.sourceSnapshot,note.text);
 assert.equal((await call('/personal-assets',{...insight.insight.assetCandidate,confirmed:true})).status,404);
 assert.equal((await call(`/personal-assets/${asset.id}/trash`,{confirmed:true})).status,200);assert.equal((await call(`/personal-assets/${asset.id}`)).status,404);
 console.log('PASS personal assets: notes CRUD, AI preview/no write/failure, provenance, versions, privacy, per-project permission, revocation, grounding and soft deletion');
}finally{if(server)await new Promise(r=>server.close(r));w?.close();await fs.rm(root,{recursive:true,force:true});}
