import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {Readable} from "node:stream";
import {openWorkspace} from "../server/storage/workspace.mjs";
import {createUlid} from "../server/storage/ids.mjs";
import {researchRoutes} from "../server/routes/research.mjs";
import {recordActivity} from "../server/domain/workspace-experience.mjs";
import {createResearch,saveResearch,getResearch,researchReference,researchConversation,researchProject,projectResearches,quickNote,libraryItems,libraryItem,workState,recentWork,listResearches,trashResearch,restoreResearch} from "../server/domain/research.mjs";
const root=await fs.mkdtemp(path.join(os.tmpdir(),"xenho-research-"));
let w;
async function call(method,routePath,params={},body,query="") {
 let status,result;
 await researchRoutes.find(r=>r.method===method&&r.path===routePath).handler({workspace:w,params,url:new URL("http://127.0.0.1"+routePath+query),req:Readable.from(body===undefined?[]:[Buffer.from(JSON.stringify(body))]),res:{writeHead(s){status=s;},end(s){result=JSON.parse(s);}}});
 return {status,...result};
}
try {
 w=await openWorkspace({xenhoHome:path.join(root,"Xenho")});
 let r=createResearch(w,{question:"为何工具越多越难开始？",notes:"自己的理解，不是已核实事实"});
 assert.equal(r.version,1);assert.equal(r.scopeId,`research:${r.id}`);assert.deepEqual(r.conversations,[]);
 const initialTime=r.updatedAt;
 workState(w,"research",r.id,{pinned:true,position:{scrollTop:345,selectionStart:8}});
 assert.equal(getResearch(w,r.id).updatedAt,initialTime,"opening and pinning never count as editing");
 r=saveResearch(w,r.id,{expectedVersion:1,openQuestions:"动机还是操作阻力？"});
 assert.equal(r.version,2);assert.equal(r.notes,"自己的理解，不是已核实事实");
 assert.throws(()=>saveResearch(w,r.id,{expectedVersion:1,notes:"overwrite"}),e=>e.status===409);
 for(const patch of [{notes:42},{question:"a".repeat(1001)},{expectedVersion:0},{unknown:true}]) assert.throws(()=>saveResearch(w,r.id,{expectedVersion:2,...patch}),e=>e.status===400);
 const raw="第一行原话\n\n保留标点、段落和 https://example.com。";
 const item=quickNote(w,{text:raw});assert.equal(item.nature,"随手记");
 assert.equal(libraryItem(w,"capture",item.id).body,raw);
 assert.equal(w.db.prepare("SELECT status FROM captures WHERE id=?").get(item.id).status,"accepted");
 assert.equal(libraryItems(w,{q:"保留标点"})[0].id,item.id);
 assert.equal(libraryItems(w,{q:"%_不存在"}).length,0);
 assert.throws(()=>quickNote(w,{text:"  "}),e=>e.status===400);
 assert.throws(()=>quickNote(w,{text:"x",sourceUrl:"javascript:alert(1)"}),e=>e.status===400);
 assert.throws(()=>researchReference(w,r.id,{kind:"capture",id:"missing"}),e=>e.status===404);
 assert.throws(()=>researchReference(w,r.id,{kind:"wiki",id:item.id}),e=>e.status===404);
 researchReference(w,r.id,{kind:"capture",id:item.id});researchReference(w,r.id,{kind:"capture",id:item.id});
 assert.equal(getResearch(w,r.id).references.length,1);
 for(const scope of [`research:${r.id}`,`research:${r.id}`,"global:assistant"]) {
   const id=`chat-${createUlid()}`;w.repository.createEntity({id,type:"ai_conversation"});
   w.db.prepare("INSERT INTO ai_conversations(id,title,scope_type,scope_id,record_json) VALUES(?,?,'global',?,?)").run(id,"一次讨论",scope,JSON.stringify({messages:[{role:"assistant",text:"这是候选"}]}));
   if(scope==="global:assistant") researchConversation(w,r.id,{conversationId:id});
 }
 assert.equal(getResearch(w,r.id).conversations.length,3,"research spans multiple conversations and can reference legacy discussion");
 assert.ok(getResearch(w,r.id).conversations.some(c=>c.scopeId==="global:assistant"));
 const bookId=createUlid(),docId=createUlid();
 w.repository.createEntity({id:bookId,type:"book"});w.repository.createEntity({id:docId,type:"book_document"});
 w.db.prepare("INSERT INTO books(id,title,source_url) VALUES(?,?,?)").run(bookId,"原书","https://example.com/book");
 w.db.prepare("INSERT INTO book_documents(id,book_id,title,body_markdown,document_order) VALUES(?,?,?,?,1)").run(docId,bookId,"第一章","可逐字核对的原文");
 assert.equal(libraryItems(w,{q:"逐字核对",kind:"source"})[0].id,docId);
 assert.equal(libraryItem(w,"source",docId).sourceUrl,"https://example.com/book");
 researchReference(w,r.id,{kind:"source",id:docId});
 w.db.prepare("UPDATE entities SET deleted_at=? WHERE id=?").run(new Date().toISOString(),bookId);
 assert.equal(getResearch(w,r.id).references.find(x=>x.id===docId).missing,true);
 w.db.prepare("UPDATE entities SET deleted_at=NULL WHERE id=?").run(bookId);
 const before=getResearch(w,r.id),requestKey=crypto.randomUUID();
 const created=researchProject(w,r.id,{requestKey,selectedText:"只选中这一段自己的理解",title:"一篇作品"});
 assert.equal(created.notebook.thought,"只选中这一段自己的理解");
 assert.equal(w.db.prepare("SELECT d.body_markdown body FROM drafts d JOIN project_primary_drafts p ON p.draft_id=d.id WHERE p.project_id=?").get(created.projectId).body,"");
 assert.equal(getResearch(w,r.id).notes,before.notes);assert.equal(getResearch(w,r.id).version,before.version);
 assert.equal(researchProject(w,r.id,{requestKey,selectedText:"只选中这一段自己的理解"}).projectId,created.projectId);
 assert.equal(getResearch(w,r.id).projects.length,1);
 const r2=createResearch(w,{question:"另一个研究"});
 researchProject(w,r2.id,{projectId:created.projectId});
 assert.equal(researchProject(w,r.id,{requestKey,selectedText:"只选中这一段自己的理解"}).projectId,created.projectId,"retry remains stable after another research is linked");
 assert.throws(()=>researchProject(w,r2.id,{requestKey,selectedText:"其他"}),e=>e.status===409);
 researchProject(w,r2.id,{projectId:created.projectId});
 assert.equal(projectResearches(w,created.projectId).length,2,"a work can draw on multiple researches");
 const second=researchProject(w,r.id,{requestKey:crypto.randomUUID(),selectedText:"另一篇的选择"});
 assert.equal(getResearch(w,r.id).projects.length,2);
 assert.notEqual(second.projectId,created.projectId);
 const count=w.db.prepare("SELECT count(*) n FROM projects").get().n;
 assert.throws(()=>researchProject(w,r.id,{requestKey:crypto.randomUUID(),selectedText:""}));
 assert.equal(w.db.prepare("SELECT count(*) n FROM projects").get().n,count);
 assert.equal(recentWork(w)[0].id,r.id,"pinned research first");
 workState(w,"research",r.id,{hidden:true});assert.ok(!recentWork(w).some(x=>x.id===r.id));
 assert.equal(recentWork(w,{includeHidden:true}).find(x=>x.id===r.id).position.scrollTop,345);
 workState(w,"research",r.id,{hidden:false});
 // 「最近打开」不再是一个面板，而是排序键的另一半：只打开过、没改过的那一条也要升上来。
 // 先建一条更新的（于是它按 updated_at 本来在前），再去「打开」一条更旧的，看后者是否越过它。
 const fresher=createResearch(w,{question:"更新的那一条，但没有被打开过"});
 const older=createResearch(w,{question:"更旧的那一条，但刚刚打开过"});
 w.db.prepare("UPDATE researches SET updated_at=? WHERE id=?").run("2020-01-01T00:00:00.000Z",older.id);
 w.db.prepare("UPDATE entities SET updated_at=? WHERE id=?").run("2020-01-01T00:00:00.000Z",older.id);
 assert.ok(recentWork(w).findIndex(x=>x.id===fresher.id)<recentWork(w).findIndex(x=>x.id===older.id),"没打开过时旧的排在后面");
 recordActivity(w,"research",older.id,{mode:"open"});
 assert.ok(recentWork(w).findIndex(x=>x.id===older.id)<recentWork(w).findIndex(x=>x.id===fresher.id),"打开过之后它越过更新的那一条");
 assert.equal(recentWork(w)[0].id,r.id,"置顶仍然压在最前面");
 assert.throws(()=>workState(w,"research",r.id,{pinned:"yes"}),e=>e.status===400);
 assert.equal((await call("PUT","/api/workspace/researches/:id",{id:r.id},{expectedVersion:1,notes:"conflict"})).status,409);
 assert.equal((await call("GET","/api/workspace/library/:kind/:id",{kind:"capture",id:item.id})).item.body,raw);
 assert.equal((await call("GET","/api/workspace/researches/:id",{id:"missing"})).status,404);
 w.db.prepare("UPDATE entities SET deleted_at=? WHERE id=?").run(new Date().toISOString(),item.id);
 assert.equal(getResearch(w,r.id).references[0].missing,true);
 assert.equal(getResearch(w,r.id).references[0].excerpt,"");
 researchReference(w,r.id,{kind:"capture",id:item.id},true);assert.equal(getResearch(w,r.id).references.length,1);
 const persisted=getResearch(w,r.id);
 w.close();w=await openWorkspace({xenhoHome:path.join(root,"Xenho")});
 assert.deepEqual(getResearch(w,r.id),persisted);
 assert.equal(recentWork(w).find(x=>x.id===r.id).position.scrollTop,345);
 // 移入回收站 → 列表里没了、单条读不到；恢复 → 原来那一条整个回来（引用也在）。
 const snapshot=getResearch(w,r.id);
 assert.equal(trashResearch(w,r.id).recoverable,true);
 assert.equal(listResearches(w).some(x=>x.id===r.id),false,"回收站里的选题不出现在列表里");
 assert.equal((await call("GET","/api/workspace/researches/:id",{id:r.id})).status,404);
 assert.throws(()=>trashResearch(w,r.id),e=>e.status===404,"已经在回收站里的不能再删一次");
 assert.equal(restoreResearch(w,r.id).id,r.id);
 assert.deepEqual(getResearch(w,r.id),snapshot,"恢复之后是原来那一条，引用和讨论都还在");
 assert.equal((await call("POST","/api/workspace/researches/:id/trash",{id:r.id},{})).research.recoverable,true);
 assert.equal((await call("POST","/api/workspace/researches/:id/restore",{id:r.id},{})).research.id,r.id);
 console.log("research: persistence, CAS, references, multi-session, many-to-many, selected text, quick capture, restoration and trash/restore passed");
} finally {w?.close();await fs.rm(root,{recursive:true,force:true});}
