import { useCallback, useEffect, useState } from "react";
import { SourceResearchPicker } from "../components/SourceResearchPicker.jsx";
import { api } from "../lib/api.js";
import { Empty, ErrorNote, Loading, PageHeader, SearchBox, ViewTabs } from "../components/ui.jsx";
import { safeUrl, sourceDate } from "../components/BriefReading.jsx";
import "./intelligence-v2.css";
const originName={internal:"自有内容与已有知识",manual:"手动记录",external:"外部资料",owned:"自有内容",self_owned:"自有内容",local:"已有知识",local_knowledge:"已有知识",unknown:"身份待核对"};
const completeness = item => item.contentStatus || item.content_status || (item.readLevel === "summary" ? "summary_only" : "");
const unavailable = item => ["deleted","expired","removed","tombstone","purged","unavailable"].includes(completeness(item)) || Boolean(item.deletedAt || item.deleted_at) || Boolean(item.expiresAt && Date.parse(item.expiresAt) <= Date.now());
const contentLabel = item => unavailable(item) ? "已清除／已到期" : completeness(item)==="full_text" || item.readLevel==="original" ? "已取得全文" : completeness(item)==="summary_only" || item.readLevel==="summary" ? "仅摘要" : "正文范围待核对";
const groupNames = {aihot:"AIHOT",t2_media:"T2 媒体",community:"社区",follow_builders:"Follow Builders",legacy:"其他来源"};
function CommentTree({comments,rootId}) {
  const byId = new Map(comments.flatMap(c=>[[c.id,c],[c.identity || c.platformId || c.platform_id,c]]).filter(([key])=>key));
  const depthOf = comment => { let depth=0,node=comment;const visited=new Set();while(node && depth<8){const parent=node.parentItemId || node.parentIdentity || node.parent_item_id || node.parentId; if(!parent || parent===rootId || visited.has(parent))break;visited.add(parent);node=byId.get(parent);if(node)depth++;}return depth; };
  return <section className="acquisition-comments"><h3>评论与回复上下文</h3><p className="intel-v2-hint">评论是用户观察和研究线索，同一讨论不会作为多份独立事实证据。</p>{comments.map(comment=>{const parent=comment.parentItemId || comment.parentIdentity || comment.parent_item_id || comment.parentId;const missing=parent && parent!==rootId && !byId.has(parent);return <div key={comment.id || comment.identity} className="acquisition-comment" style={{"--comment-depth":depthOf(comment)}}><header>{comment.author || "作者信息不可用"} · {sourceDate(comment.publishedAt || comment.created_at)}{comment.metadata?.score!==undefined ? ` · 评分 ${comment.metadata.score}` : ""}{comment.metadata?.sortBuckets?.length ? ` · ${comment.metadata.sortBuckets.join(" / ")}` : ""}</header>{missing && <p className="intel-channel-error">父级上下文尚未取得</p>}<p>{unavailable(comment) ? "评论已删除或保留期已到，不再展示内容。" : completeness(comment)==="context_missing" ? "这条父级上下文尚未取得，不能据此推断原帖内容。" : comment.body || "没有可展示的评论正文"}</p>{safeUrl(comment.url) && <a href={safeUrl(comment.url)} target="_blank" rel="noreferrer">查看评论 ↗</a>}</div>;})}</section>;
}
function Resource({item,onGo,onLink}) {
  const isSeed=item.type==="seed",isBrief=item.type==="brief";
  const [full,setFull]=useState(null),[extra,setExtra]=useState(null),[error,setError]=useState(null),[loading,setLoading]=useState(false);
  async function read(){
    if(isSeed || isBrief || full || loading)return;setLoading(true);
    try {
      const response=await fetch(`/api/workspace/acquisition/sources/${encodeURIComponent(item.id)}`);
      if(response.status===404){const result=await api.intelligenceSourceDetail(item.id);setFull(result.source || result);setExtra(null);}
      else {const result=await response.json();if(!response.ok || result.ok===false)throw new Error(result.error || "读取资料失败");setFull(result.source);setExtra(result);}
      setError(null);
    }catch(e){setError(e);}finally{setLoading(false);}
  }
  if(isBrief)return <article className="intel-v2-resource"><h2><button className="text-action" onClick={()=>onGo("intel-detail",item.id)}>{item.title}</button></h2><p className="intel-v2-hint">收藏情报 · {sourceDate(item.editionDate || item.createdAt)}</p><p>{item.summary}</p></article>;
  const source=full || item, gone=unavailable(source), body=full ? full.body || full.summary || "尚未取得正文" : item.body || item.summary || "尚无正文";
  const rights=source.rights || {}, discoveries=extra?.discoveries || [], comments=(extra?.comments || []).filter(c=>c.sourceKind==="comment" || c.contentKind==="comment"), segments=extra?.segments || [];
  return <details className="intel-v2-resource" onToggle={event=>{if(event.currentTarget.open)void read();}}><summary><strong>{isSeed ? item.take : item.title}</strong><span>{isSeed ? "灵感种子" : item.provider==="manual" ? "手动资料" : originName[item.originKind || item.originType] || "身份待核对"} · {sourceDate(item.publishedAt || item.createdAt)}{!isSeed ? ` · ${contentLabel(source)}` : ""}{(item.sourceKind || item.contentKind)==="comment" ? " · 评论（同一讨论不算独立证据）" : ""}</span></summary>
    {loading && <p role="status">正在读取正文…</p>}{error && <ErrorNote error={error} what="读取资料" onRetry={read}/>}
    {!isSeed && source.acquisition && <div className="acquisition-resource-meta"><span>{source.platform || source.provider}</span><span>{rights.aiAllowed===true ? "已允许 AI 处理" : "外部 AI 处理未授权"}</span><span>{rights.exportAllowed===true ? "已允许导出" : "导出未授权"}</span>{source.expiresAt && <span>保留至 {sourceDate(source.expiresAt)}</span>}</div>}
    {!isSeed && (source.sourceKind==="external_digest" || source.metadata?.secondarySource) && <p className="intel-v2-hint">这是上游整理的报告，报告中的摘要和判断需结合所引原文核对。</p>}
    <p className={`intel-resource-body${!isSeed && body.length>12000 ? " intel-resource-body--long" : ""}`} tabIndex={!isSeed && body.length>12000 ? 0 : undefined} aria-label={!isSeed && body.length>12000 ? "完整正文，可滚动阅读" : undefined}>{isSeed ? item.sourceTitle || item.trigger || item.body || item.take : gone ? "这条资料已删除或保留期已到，正文不再展示。" : body}</p>
    {safeUrl(source.url || item.sourceUrl) && <a href={safeUrl(source.url || item.sourceUrl)} target="_blank" rel="noreferrer">查看原文 ↗</a>}
    {!!discoveries.length && <section className="acquisition-discoveries"><h3>发现渠道</h3><ul>{discoveries.map((d,index)=><li key={d.id || index}>{d.channelName || d.channel_name || d.name || d.channel_id || d.channelId}{d.discoveredAt || d.discovered_at || d.last_seen_at ? ` · ${sourceDate(d.discoveredAt || d.discovered_at || d.last_seen_at)}` : ""}{d.active===false || d.active===0 || d.selected===0 ? " · 已退出上游精选，原始引用保留" : ""}</li>)}</ul></section>}
    {!gone && !!segments.length && <details className="acquisition-segments"><summary>按段阅读 · {segments.length} 段</summary><p className="intel-v2-hint">同一文档的分段仅用于阅读与引用，不会算成多个独立来源。</p>{segments.map((segment,index)=><section key={segment.id || index}><h4>{segment.speaker || segment.metadata?.speaker || `第 ${index+1} 段`}{segment.startTime || segment.start_time ? ` · ${segment.startTime || segment.start_time}` : ""}</h4><p className="intel-resource-body">{segment.text || segment.body || segment.content || (Number.isInteger(segment.start_offset) ? source.body?.slice(segment.start_offset,segment.end_offset) : "")}</p></section>)}</details>}
    {!gone && !!comments.length && <CommentTree comments={comments} rootId={source.rootItemId || source.id}/>}
    {!isSeed && <div className="intel-v2-actions"><button className="btn" disabled={gone || loading || Boolean(error)} onClick={()=>onLink(source)}>带入选题</button></div>}
  </details>;
}
export function IntelligenceResources({onGo}) {
  const [data,setData]=useState(null),[error,setError]=useState(null),[search,setSearch]=useState(""),[tab,setTab]=useState("all"),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false);
  const [linking,setLinking]=useState(null),[contentFilter,setContentFilter]=useState("all"),[platformFilter,setPlatformFilter]=useState("all"),[groupFilter,setGroupFilter]=useState("all");
  const [note,setNote]=useState({title:"",body:"",url:""});
  const load=useCallback(async()=>{try{const [intel,seeds,feed]=await Promise.all([api.intelligence(),api.seeds(),api.intelligenceFeed()]);setData({sources:intel.collectedSources || intel.sources || [],seeds:seeds.seeds || seeds.items || [],briefs:(feed.briefs || []).filter(item=>item.saved)});setError(null);}catch(e){setError(e);}},[]);
  useEffect(()=>{void load();},[load]);
  async function save(event){event.preventDefault();if(!note.body.trim())return;setBusy(true);try{await api.intelligenceSource({...note,title:note.title.trim() || note.body.trim().slice(0,80)});setAdding(false);setTab("manual");setSearch("");setNote({title:"",body:"",url:""});await load();}catch(e){setError(e);}finally{setBusy(false);}}
  const items=[...(data?.briefs || []).map(item=>({...item,type:"brief"})),...(data?.sources || []).map(item=>({...item,type:"source"})),...(data?.seeds || []).map(item=>({...item,type:"seed"}))].filter(item=>tab==="all" || (tab==="saved" ? item.type==="brief" : tab==="manual" ? item.type==="seed" || item.provider==="manual" : item.type==="source" && item.provider!=="manual")).filter(item=>contentFilter==="all" || (contentFilter==="full" ? contentLabel(item)==="已取得全文" : contentFilter==="summary" ? contentLabel(item)==="仅摘要" : unavailable(item))).filter(item=>platformFilter==="all" || (item.platform || item.provider)===platformFilter).filter(item=>groupFilter==="all" || (item.sourceGroup || item.source_group || item.metadata?.sourceGroup)===groupFilter).filter(item=>`${item.title || ""} ${item.take || ""} ${item.body || ""} ${item.summary || ""}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="intelligence-v2"><PageHeader title="资料" aside={<button className="btn btn-primary" onClick={()=>setAdding(!adding)}>{adding ? "收起记录" : "添加资料或灵感"}</button>}/><div className="intel-v2-toolbar"><ViewTabs items={[{key:"all",label:"全部资料"},{key:"saved",label:"收藏情报"},{key:"external",label:"调研资料"},{key:"manual",label:"灵感与手动记录"}]} value={tab} onChange={setTab} label="资料类型"/><SearchBox value={search} onChange={setSearch} ariaLabel="搜索情报资料" placeholder="搜索资料与灵感"/></div><div className="acquisition-resource-filters"><label>正文范围<select aria-label="正文范围" value={contentFilter} onChange={e=>setContentFilter(e.target.value)}><option value="all">全部范围</option><option value="full">已取得全文</option><option value="summary">仅摘要</option><option value="unavailable">已清除／已到期</option></select></label><label>平台<select aria-label="平台" value={platformFilter} onChange={e=>setPlatformFilter(e.target.value)}><option value="all">全部平台</option>{[...new Set((data?.sources || []).map(s=>s.platform || s.provider).filter(Boolean))].map(value=><option value={value} key={value}>{value}</option>)}</select></label><label>来源组<select aria-label="来源组" value={groupFilter} onChange={e=>setGroupFilter(e.target.value)}><option value="all">全部来源组</option>{Object.entries(groupNames).map(([value,name])=><option value={value} key={value}>{name}</option>)}</select></label></div><p className="intel-v2-hint">汇集收藏情报、最近 500 条采集资料与已保存的灵感种子。资料被保留不代表已通过精选校验。</p><div className="intel-v2-actions"><button className="text-action" onClick={()=>onGo("hot")}>浏览 AI 热点</button><button className="text-action" onClick={()=>onGo("seeds")}>管理灵感种子</button></div>{error && <ErrorNote error={error} what="读取资料" onRetry={load}/>}{adding && <form className="intel-v2-form" onSubmit={save}><label>标题（可选）<input maxLength={300} value={note.title} onChange={e=>setNote({...note,title:e.target.value})}/></label><label>原始内容<textarea required rows={5} value={note.body} onChange={e=>setNote({...note,body:e.target.value})}/></label><label>来源链接（可选）<input type="url" value={note.url} onChange={e=>setNote({...note,url:e.target.value})}/></label><p className="intel-v2-hint">保留原始记录；AI 后续给出的解读不会覆盖它。</p><button className="btn btn-primary" disabled={busy || !note.body.trim()}>确认保存资料</button></form>}{!data ? <Loading rows={4}/> : !items.length ? <Empty><h2>{search ? "没有匹配的资料" : "这里保留情报依据与自己的灵感"}</h2><p>收藏情报、采集到的文章、评论、手动记录与灵感种子会保留各自的来源。</p></Empty> : <div className="intel-v2-list">{items.map(item=><Resource key={`${item.type}:${item.id}`} item={item} onGo={onGo} onLink={setLinking}/>)}</div>}{linking && <SourceResearchPicker source={linking} onClose={()=>setLinking(null)} onGo={onGo}/>}</div>;
}
