import { IntelligenceHeader } from "../components/IntelligenceHeader.jsx";
import { IntelligenceNav } from "../components/IntelligenceNav.jsx";
import { useCallback, useEffect, useState } from "react";
import { api } from "../lib/api.js";
import { ErrorNote, Loading } from "../components/ui.jsx";
import { safeUrl, sourceDate } from "../components/BriefReading.jsx";
import "./intelligence-v2.css";
import { AcquisitionPanel } from "./AcquisitionPanel.jsx";
const categories={official:"一手发布",practice:"实践案例",questions:"用户问题",deep:"深度分析",adjacent:"相邻领域"};
const healthName={never:"尚未采集",ok:"可用",empty:"本次无新内容",not_modified:"内容未变",partial:"部分可用",failed:"采集失败",manual:"需要手动收集"};
export function IntelligenceChannels({onGo}) {
  const [data,setData]=useState(null),[error,setError]=useState(null),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{setData(await api.intelligenceChannels());setError(null);}catch(e){setError(e);}},[]);
  useEffect(()=>{void load();},[load]);
  async function save(body,id){setBusy(true);try{await api.intelligenceChannelSave(body,id);setEditing(null);await load();}catch(e){setError(e);}finally{setBusy(false);}}
  return <div className="intel-workspace intelligence-v2 intel-channels-page"><IntelligenceNav current="intel-channels" onGo={onGo} /><IntelligenceHeader title="信源管理" aside={<button className="btn btn-primary" onClick={()=>setEditing({name:"",url:"",category:"practice",format:"rss",enabled:true})}>添加信源</button>}/><p className="intel-v2-hint">信源是持续关注的发布渠道；一篇文章及其评论不会被算成多个独立信源。</p>{error && <ErrorNote error={error} what="管理信源" onRetry={load}/>}{editing && <form className="intel-v2-form" onSubmit={e=>{e.preventDefault();void save(editing,editing.id);}}><label>名称<input required value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>订阅地址<input type="url" required value={editing.url} onChange={e=>setEditing({...editing,url:e.target.value})}/></label><label>用途<select value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}>{Object.entries(categories).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>读取方式<select value={editing.format} onChange={e=>setEditing({...editing,format:e.target.value})}><option value="rss">RSS</option><option value="atom">Atom</option><option value="github">GitHub 发布</option><option value="manual">手动收集</option></select></label><div className="intel-v2-actions"><button className="btn btn-primary" disabled={busy}>保存信源</button><button className="btn" type="button" onClick={()=>setEditing(null)}>取消</button></div></form>}<AcquisitionPanel/><details className="acquisition-legacy" open><summary>旧订阅配置与自定义信源</summary>{!data ? <Loading rows={5}/> : <><p className="intel-v2-hint">{data.summary?.total ?? data.channels.length} 个渠道 · {data.summary?.enabled ?? 0} 个已启用 · {data.summary?.failed ?? 0} 个采集失败</p><div className="intel-v2-list">{data.channels.map(channel=><article key={channel.id}><header><span className="intel-v2-state">{categories[channel.category] || channel.category}</span><h2>{channel.name}</h2><span>{channel.enabled ? healthName[channel.health] || "尚未采集" : "已暂停"}</span></header><p className="intel-v2-hint">最近成功：{sourceDate(channel.lastSuccessAt) || "暂无"} · 最近尝试：{sourceDate(channel.lastAttemptAt) || "暂无"}{channel.lastItemCount!==undefined ? ` · ${channel.lastItemCount} 条` : ""}</p>{channel.lastError && <p className="intel-channel-error">{channel.lastError}</p>}<div className="intel-v2-actions">{safeUrl(channel.siteUrl || channel.url) && <a href={safeUrl(channel.siteUrl || channel.url)} target="_blank" rel="noreferrer">查看来源 ↗</a>}<button className="text-action" disabled={busy} onClick={()=>setEditing({...channel})}>编辑</button><button className="btn btn-sm" disabled={busy} onClick={()=>save({enabled:!channel.enabled},channel.id)}>{channel.enabled ? "暂停" : "启用"}</button></div></article>)}</div></>}</details></div>;
}
