import { useCallback, useEffect, useState } from "react";
import { api } from "../lib/api.js";
import "./intelligence.css";

const PROVIDERS = {local: "我的记录与素材", web: "主题搜索", aihot: "AI 行业信息", x: "X 关注账号", reddit: "Reddit 社区", xiaohongshu: "小红书公开内容", douyin: "抖音公开内容"};
const sourceLabel = key => key === "manual" ? "手动记录" : PROVIDERS[key] || key;
const stageLabel = value => String(value || "").replace(/读取 (local|web|aihot|xiaohongshu|douyin|x|reddit)/, (_, key) => `读取${sourceLabel(key)}`);
const STATUS = {queued:"等待调研",running:"正在调研",done:"已完成",partial:"部分完成",failed:"调研失败",cancelled:"已取消"};
const EMPTY = {profiles:[],runs:[],cards:[],sources:[],capabilities:{}};
const fresh = () => ({name:"",query:"",frequency:"manual",providers:["local","web"],accounts:[],subreddits:[],limit:5,enabled:true,paidApproved:false});
const listText = value => Array.isArray(value) ? value.join("；") : String(value || "");
const time = value => value ? new Date(value).toLocaleString("zh-CN", {month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}) : "";
const safeUrl = value => { try { const url = new URL(value); return ["https:","http:"].includes(url.protocol) ? url.href : null; } catch { return null; } };

function IntelligenceSourceBody({source}) {
  const [full,setFull] = useState(null), [loading,setLoading] = useState(false), [error,setError] = useState("");
  const load = async () => {
    if(!source.bodyTruncated || full || loading)return;
    setLoading(true);setError("");
    try {const result=await api.intelligenceSourceDetail(source.id);setFull(result.source);}
    catch(e){setError(e.message);}finally{setLoading(false);}
  };
  useEffect(()=>{void load();},[source.id]);
  return <>{loading && <p className="intel-hint" role="status">正在读取全文…</p>}{error && <div className="intel-error" role="alert">{error}<button className="btn" onClick={load}>重试读取</button></div>}<p className="intel-source-body">{full?.body || source.body || "尚未读取正文"}</p>{source.bodyTruncated && !full && !loading && !error && <button className="btn" onClick={load}>读取全文</button>}</>;
}
function IntelligenceSourceDisclosure({source,children,className}) {
  const [open,setOpen] = useState(false);
  return <details className={className} onToggle={event=>setOpen(event.currentTarget.open)}><summary>{children}</summary>{open && <IntelligenceSourceBody key={source.id} source={source}/>} {open && safeUrl(source.url) && <a href={safeUrl(source.url)} target="_blank" rel="noreferrer">查看原文 ↗</a>}</details>;
}

export function Intelligence({view, initialAction, onGo}) {
  const [data,setData] = useState(EMPTY), [loading,setLoading] = useState(true), [error,setError] = useState("");
  const [busy,setBusy] = useState(""), [notice,setNotice] = useState(""), [filter,setFilter] = useState("new");
  const [editing,setEditing] = useState(null), [note,setNote] = useState({title:"",body:"",url:""});
  const [search,setSearch] = useState("");
  const [recovery,setRecovery] = useState({});
  const page = view === "intel-settings" ? "settings" : view === "intel-inbox" ? "inbox" : "discover";
  const load = useCallback(async (quiet = false) => { try {const result=await api.intelligence();setData({...EMPTY,...result});if(!quiet)setError("");} catch(e){setError(e.message);} finally {setLoading(false);} },[]);
  useEffect(() => {void load();},[load]);
  useEffect(() => {if(view === "intel-settings" && initialAction === "new")setEditing(fresh());},[view,initialAction]);
  useEffect(() => {const timer=setInterval(() => {if(!document.hidden) void load(true);},5000);return () => clearInterval(timer);},[load]);
  const act = async (key, fn, message="") => {setBusy(key);setError("");setNotice("");try {const result=await fn();await load();setNotice(message);return result;}catch(e){setError(e.message);return null;}finally{setBusy("");}};
  const openCard = async card => {if(card.researchId){onGo("research",card.researchId);return;} const result=await act(card.id,()=>api.intelligenceAdopt(card.id));if(result?.research?.id)onGo("research",result.research.id);};
  const cards=data.cards.filter(card => filter === "all" || (filter === "adopted" ? Boolean(card.researchId) : card.status===filter && !card.researchId));
  const sources = data.sources.filter(source => `${source.title} ${source.body}`.toLowerCase().includes(search.toLowerCase()));
  const active=data.runs.filter(run=>["queued","running"].includes(run.status));
  const scopeChange = patch => setEditing(current=>({...current,...patch,paidApproved:false}));
  const saveProfile = async event => {event.preventDefault();const result=await act("profile",()=>api.intelligenceProfile(editing),"关注方向已保存");if(result)setEditing(null);};
  const saveNote = async event => {event.preventDefault();const result=await act("note",()=>api.intelligenceSource(note),"已收集，下次相关调研会参考这条记录");if(result)setNote({title:"",body:"",url:""});};
  return <div className="intelligence">
    <header className="intel-header"><div><h1>{page === "settings" ? "关注与调研" : page === "inbox" ? "收集箱" : "选题发现"}</h1><p>{page === "settings" ? "确定关注的问题，让 AI 持续寻找相关信息。" : page === "inbox" ? "调研找到的资料，和你随手记下的疑问与灵感。" : "从相关讨论与个人积累中，发现值得展开的问题。"}</p></div>{page !== "settings" && <button className="btn" onClick={()=>onGo("intel-settings")}>管理调研</button>}{page === "settings" && <button className="btn btn-primary" onClick={()=>setEditing(fresh())}>新增关注方向</button>}</header>
    {error && <div className="intel-error" role="alert">{error}<button className="btn" onClick={()=>load()}>重新加载</button></div>}
    {notice && <p className="intel-notice" role="status">{notice}</p>}
    {loading ? <p role="status">正在读取情报…</p> : <>
      {active.length>0 && <div className="intel-active" aria-live="polite">{active.map(run=><div key={run.id}><span>{data.profiles.find(p=>p.id===run.profileId)?.name || "调研"} · {STATUS[run.status]}{run.stage ? ` · ${stageLabel(run.stage)}` : ""}</span><button className="btn" disabled={Boolean(busy)} onClick={()=>act(run.id,()=>api.intelligenceCancel(run.id))}>取消调研</button></div>)}</div>}
      {page === "discover" && <>
        <div className="intel-filters" aria-label="选题状态">{[["new","待挑选"],["watch","继续观察"],["adopted","已采用"],["dismissed","不感兴趣"],["all","全部"]].map(([key,label])=><button key={key} className={`btn ${filter===key ? "is-active" : ""}`} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</div>
        {!data.profiles.length && <div className="intel-empty"><h2>先告诉 AI，你在关注什么</h2><p>例如：AI 编程中反复出现的问题。选择相关来源后，AI 会调研、连接 Wiki，并提出有依据的选题候选。</p><button className="btn btn-primary" onClick={()=>onGo("intel-settings","new")}>设置第一个关注方向</button></div>}
        {data.profiles.length>0 && !cards.length && <div className="intel-empty"><h2>这里还没有选题</h2><p>完成一次调研后，有依据的候选会出现在这里。信息不足时不会为凑数生成卡片。</p><button className="btn" onClick={()=>onGo("intel-settings")}>查看方向并开始调研</button></div>}
        <div className="intel-cards">{cards.map(card=><article className="intel-card" key={card.id}><div className="intel-meta"><span>{card.researchId ? "已采用" : card.status === "watch" ? "继续观察" : card.status === "dismissed" ? "不感兴趣" : "选题候选"}</span><span>{time(card.updatedAt)}</span></div><h2>{card.question}</h2><p className="intel-why">{card.why}</p><dl><dt>表达角度</dt><dd>{card.angle}</dd>{card.audience && <><dt>适合谁看</dt><dd>{card.audience}</dd></>}{card.wiki?.length>0 && <><dt>与你的连接</dt><dd>{card.wiki.map(wiki=><div key={wiki.id}><button className="intel-link" onClick={()=>onGo("entries",wiki.id)}>{wiki.title}</button>{wiki.reason && ` · ${wiki.reason}`}</div>)}</dd></>}{listText(card.gaps) && <><dt>还缺什么</dt><dd>{listText(card.gaps)}</dd></>}</dl><details><summary>查看依据 · {card.evidence?.length || 0} 条</summary><p className="intel-hint">上方是 AI 的候选解释；以下为实际收集到的来源与摘录。</p>{card.evidence?.map((e,index)=>{const source=data.sources.find(s=>s.id===e.sourceId);const url=safeUrl(source?.url);return <div className="intel-evidence" key={`${e.sourceId}-${index}`}><strong>{source?.title || "来源暂不可用"}</strong><p className="intel-hint">{sourceLabel(source?.provider)} {source?.readLevel && ` · ${source.readLevel === "original" ? "已读取原文" : "读取范围有限"}`} {time(source?.publishedAt)}</p><blockquote>{e.quote}</blockquote>{url && <a href={url} target="_blank" rel="noreferrer">查看原文 ↗</a>}{source?.body && <IntelligenceSourceDisclosure source={source}>已读取的内容</IntelligenceSourceDisclosure>}</div>;})}</details><footer><button className="btn btn-primary" disabled={Boolean(busy)} onClick={()=>openCard(card)}>{busy===card.id ? "处理中…" : card.researchId ? "继续讨论" : "采用并一起讨论"}</button>{!card.researchId && <><button className="btn" disabled={Boolean(busy)} onClick={()=>act(card.id,()=>api.intelligenceCard(card.id,{status:card.status==="watch" ? "new":"watch"}))}>{card.status==="watch" ? "放回待挑选" : "留着观察"}</button><button className="btn" disabled={Boolean(busy)} onClick={()=>act(card.id,()=>api.intelligenceCard(card.id,{status:card.status==="dismissed" ? "new":"dismissed"}))}>{card.status==="dismissed" ? "恢复候选" : "不感兴趣"}</button></>}</footer></article>)}</div>
      </>}
      {page === "inbox" && <><form className="intel-note" onSubmit={saveNote}><h2>记下一条线索</h2><label>标题<input aria-label="标题" required maxLength={300} value={note.title} onChange={e=>setNote({...note,title:e.target.value})} placeholder="一个疑问、一个观察，或一篇资料"/></label><label>内容<textarea aria-label="内容" required rows={3} value={note.body} onChange={e=>setNote({...note,body:e.target.value})} placeholder="写下你的想法，或粘贴需要参考的内容"/></label><label>来源链接（可选）<input type="url" value={note.url} onChange={e=>setNote({...note,url:e.target.value})} placeholder="https://"/></label><button className="btn btn-primary" disabled={Boolean(busy) || !note.title.trim() || !note.body.trim()}>保存到收集箱</button></form><div className="intel-section-head"><h2>已收集 · {data.sources.length}</h2><input aria-label="搜索收集内容" type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索收集内容"/></div>{!sources.length && <p className="intel-empty">{search ? "没有匹配的内容" : "调研来源和手动记录会汇集在这里。"}</p>}{sources.map(source=><IntelligenceSourceDisclosure className="intel-source" key={source.id} source={source}>{source.title}<span>{sourceLabel(source.provider)} · {time(source.createdAt)}</span></IntelligenceSourceDisclosure>)}</>}
      {page === "settings" && <>
        <p className="intel-schedule-note">自动调研仅在工作台开启时执行；关闭期间错过的计划，会在下次开启后补跑。通用平台热榜不参与调研。</p>
        {editing && <form className="intel-profile-form" onSubmit={saveProfile}><h2>{editing.id ? "编辑关注方向" : "新增关注方向"}</h2><label>方向名称<input required maxLength={120} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} placeholder="例如：AI 编程的真实使用问题"/></label><label>你想了解什么<textarea aria-label="你想了解什么" required rows={3} value={editing.query} onChange={e=>setEditing({...editing,query:e.target.value})} placeholder="关注谁遇到了什么问题、哪些争议或变化值得深入？"/></label><fieldset><legend>调研来源</legend>{Object.entries(PROVIDERS).map(([key,label])=><label className="intel-check" key={key}><input type="checkbox" checked={editing.providers.includes(key)} onChange={e=>scopeChange({providers:e.target.checked ? [...editing.providers,key] : editing.providers.filter(p=>p!==key)})}/>{label}{data.capabilities[key] === false && <span className="intel-hint">（尚未配置）</span>}</label>)}</fieldset>{editing.providers.some(p=>["xiaohongshu","douyin"].includes(p)) && <p className="intel-hint">按主题查找公开内容；受登录限制或无法读取的页面会明确记录，不会据此编造结论。</p>}{editing.providers.includes("x") && <label>X 账号（最多 5 个，逗号分隔）<input required value={editing.accounts.join(",")} onChange={e=>scopeChange({accounts:e.target.value.split(/[,，]/).map(s=>s.trim())})} placeholder="账号名，不含网址"/></label>}{editing.providers.includes("reddit") && <label>Reddit 社区（最多 5 个，逗号分隔）<input required value={editing.subreddits.join(",")} onChange={e=>scopeChange({subreddits:e.target.value.split(/[,，]/).map(s=>s.trim())})} placeholder="例如：LocalLLaMA"/></label>}<div className="intel-form-row"><label>调研频率<select aria-label="调研频率" value={editing.frequency} onChange={e=>scopeChange({frequency:e.target.value})}><option value="manual">手动发起</option><option value="daily">每天</option><option value="weekly">每周</option></select></label><label>每个账号／社区最多读取<input type="number" min="1" max="20" required value={editing.limit} onChange={e=>scopeChange({limit:Number(e.target.value)})}/></label></div>{editing.providers.some(p=>p==="x" || p==="reddit") && <label className="intel-check intel-paid"><input type="checkbox" required checked={editing.paidApproved} onChange={e=>setEditing({...editing,paidApproved:e.target.checked})}/>同意按本方向保存的账号、社区和条数上限调用付费采集服务；费用由已配置的服务商收取。</label>}<label className="intel-check"><input type="checkbox" checked={editing.enabled} onChange={e=>setEditing({...editing,enabled:e.target.checked})}/>启用此关注方向</label><footer><button className="btn btn-primary" disabled={Boolean(busy) || !editing.providers.length || !editing.name.trim() || !editing.query.trim() || editing.accounts.length>5 || editing.subreddits.length>5}>保存关注方向</button><button type="button" className="btn" onClick={()=>setEditing(null)}>取消</button></footer></form>}
        {!data.profiles.length && !editing && <p className="intel-empty">还没有关注方向。先设置一个你真正关心的问题。</p>}
        {data.profiles.map(profile=><article className="intel-profile" key={profile.id}><div><h2>{profile.name}</h2><p>{profile.query}</p><p className="intel-hint">{profile.providers.map(p=>PROVIDERS[p] || p).join(" · ")} · {{manual:"手动",daily:"每日",weekly:"每周"}[profile.frequency]}{!profile.enabled && " · 已暂停"}</p></div><div className="intel-actions"><button className="btn btn-primary" disabled={Boolean(busy) || active.some(r=>r.profileId===profile.id)} onClick={()=>act(profile.id,()=>api.intelligenceRun(profile.id),"调研已开始，可在选题发现查看结果")}>现在调研</button><button className="btn" onClick={()=>setEditing({...fresh(),...profile})}>编辑</button><button className="btn" disabled={Boolean(busy)} onClick={()=>act(profile.id,()=>api.intelligenceProfile({...profile,enabled:!profile.enabled}))}>{profile.enabled ? "暂停" : "启用"}</button></div></article>)}
        <section className="intel-history"><h2>调研记录</h2>{!data.runs.length && <p className="intel-hint">首次执行后，这里会记录实际来源覆盖和结果。</p>}{data.runs.map(run=><details key={run.id} className="intel-run"><summary><span>{data.profiles.find(p=>p.id===run.profileId)?.name || "调研"}</span><span>{STATUS[run.status] || run.status} · {time(run.createdAt)}</span></summary>{run.stage && <p>{stageLabel(run.stage)}</p>}{run.error && <p className="intel-error">{run.error}</p>}{run.coverage?.map((c,index)=><p key={`${c.provider}-${index}`}>{PROVIDERS[c.provider] || c.provider} · {c.count || 0} 条 · {c.error || STATUS[c.status] || c.status}</p>)}{run.coverage?.filter(c=>c.uncertain).map(c=><label className="intel-recovery" key={c.provider}>{PROVIDERS[c.provider] || c.provider} 采集恢复 ID<p className="intel-hint">上次请求结果未确认。请从服务商任务记录填写已有采集 ID，避免重复付费；没有 ID 时不会重新发起付费采集。</p><input value={recovery[run.id]?.[c.provider] || ""} placeholder="s_…" onChange={e=>setRecovery({...recovery,[run.id]:{...recovery[run.id],[c.provider]:e.target.value}})}/></label>)}{["failed","partial","cancelled"].includes(run.status) && <button className="btn" disabled={Boolean(busy)} onClick={()=>act(run.id,()=>api.intelligenceRetry(run.id,{snapshotIds:recovery[run.id] || {}}),"已重新安排调研")}>重试调研</button>}</details>)}</section>
      </>}
    </>}
  </div>;
}
