import { useCallback, useEffect, useState } from "react";
import { SourceResearchPicker } from "../components/SourceResearchPicker.jsx";
import { api } from "../lib/api.js";
import { Empty, ErrorNote, Loading, PageHeader, SearchBox, ViewTabs } from "../components/ui.jsx";
import { safeUrl, sourceDate } from "../components/BriefReading.jsx";
import "./intelligence-v2.css";
const originName={internal:"自有内容与已有知识",manual:"手动记录",external:"外部资料",owned:"自有内容",self_owned:"自有内容",local:"已有知识",local_knowledge:"已有知识",unknown:"身份待核对"};
function Resource({item,onGo,onLink}) {
  const isSeed=item.type==="seed",isBrief=item.type==="brief";
  const [full,setFull]=useState(null),[error,setError]=useState(null),[loading,setLoading]=useState(false);
  async function read(){if(isSeed || isBrief || full || loading)return;setLoading(true);try{const result=await api.intelligenceSourceDetail(item.id);setFull(result.source || result);setError(null);}catch(e){setError(e);}finally{setLoading(false);}}
  if(isBrief)return <article className="intel-v2-resource"><h2><button className="text-action" onClick={()=>onGo("intel-detail",item.id)}>{item.title}</button></h2><p className="intel-v2-hint">收藏情报 · {sourceDate(item.editionDate || item.createdAt)}</p><p>{item.summary}</p></article>;
  return <details className="intel-v2-resource" onToggle={event=>{if(event.currentTarget.open)void read();}}><summary><strong>{isSeed ? item.take : item.title}</strong><span>{isSeed ? "灵感种子" : item.provider==="manual" ? "手动资料" : originName[item.originKind || item.originType] || "身份待核对"} · {sourceDate(item.publishedAt || item.createdAt)}{(item.sourceKind || item.contentKind)==="comment" ? " · 评论（同一讨论不算独立证据）" : ""}</span></summary>{loading && <p role="status">正在读取正文…</p>}{error && <ErrorNote error={error} what="读取资料" onRetry={read}/>}<p className="intel-resource-body">{isSeed ? item.sourceTitle || item.trigger || item.body || item.take : full?.body || item.body || "尚无正文"}</p>{safeUrl(item.url || item.sourceUrl) && <a href={safeUrl(item.url || item.sourceUrl)} target="_blank" rel="noreferrer">查看原文 ↗</a>}{!isSeed && <div className="intel-v2-actions"><button className="btn" onClick={()=>onLink(full || item)}>带入选题</button></div>}</details>;
}
export function IntelligenceResources({onGo}) {
  const [data,setData]=useState(null),[error,setError]=useState(null),[search,setSearch]=useState(""),[tab,setTab]=useState("all"),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false);
  const [linking,setLinking]=useState(null);
  const [note,setNote]=useState({title:"",body:"",url:""});
  const load=useCallback(async()=>{try{const [intel,seeds,feed]=await Promise.all([api.intelligence(),api.seeds(),api.intelligenceFeed()]);setData({sources:intel.collectedSources || intel.sources || [],seeds:seeds.seeds || seeds.items || [],briefs:(feed.briefs || []).filter(item=>item.saved)});setError(null);}catch(e){setError(e);}},[]);
  useEffect(()=>{void load();},[load]);
  async function save(event){event.preventDefault();if(!note.body.trim())return;setBusy(true);try{await api.intelligenceSource({...note,title:note.title.trim() || note.body.trim().slice(0,80)});setAdding(false);setTab("manual");setSearch("");setNote({title:"",body:"",url:""});await load();}catch(e){setError(e);}finally{setBusy(false);}}
  const items=[...(data?.briefs || []).map(item=>({...item,type:"brief"})),...(data?.sources || []).map(item=>({...item,type:"source"})),...(data?.seeds || []).map(item=>({...item,type:"seed"}))].filter(item=>tab==="all" || (tab==="saved" ? item.type==="brief" : tab==="manual" ? item.type==="seed" || item.provider==="manual" : item.type==="source" && item.provider!=="manual")).filter(item=>`${item.title || ""} ${item.take || ""} ${item.body || ""} ${item.summary || ""}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="intelligence-v2"><PageHeader title="资料" aside={<button className="btn btn-primary" onClick={()=>setAdding(!adding)}>{adding ? "收起记录" : "添加资料或灵感"}</button>}/><div className="intel-v2-toolbar"><ViewTabs items={[{key:"all",label:"全部资料"},{key:"saved",label:"收藏情报"},{key:"external",label:"调研资料"},{key:"manual",label:"灵感与手动记录"}]} value={tab} onChange={setTab} label="资料类型"/><SearchBox value={search} onChange={setSearch} ariaLabel="搜索情报资料" placeholder="搜索资料与灵感"/></div><p className="intel-v2-hint">汇集收藏情报、最近 500 条采集资料与已保存的灵感种子。资料被保留不代表已通过精选校验。</p><div className="intel-v2-actions"><button className="text-action" onClick={()=>onGo("hot")}>浏览 AI 热点</button><button className="text-action" onClick={()=>onGo("seeds")}>管理灵感种子</button></div>{error && <ErrorNote error={error} what="读取资料" onRetry={load}/>}{adding && <form className="intel-v2-form" onSubmit={save}><label>标题（可选）<input maxLength={300} value={note.title} onChange={e=>setNote({...note,title:e.target.value})}/></label><label>原始内容<textarea required rows={5} value={note.body} onChange={e=>setNote({...note,body:e.target.value})}/></label><label>来源链接（可选）<input type="url" value={note.url} onChange={e=>setNote({...note,url:e.target.value})}/></label><p className="intel-v2-hint">保留原始记录；AI 后续给出的解读不会覆盖它。</p><button className="btn btn-primary" disabled={busy || !note.body.trim()}>确认保存资料</button></form>}{!data ? <Loading rows={4}/> : !items.length ? <Empty><h2>{search ? "没有匹配的资料" : "这里保留情报依据与自己的灵感"}</h2><p>收藏情报、采集到的文章、评论、手动记录与灵感种子会保留各自的来源。</p></Empty> : <div className="intel-v2-list">{items.map(item=><Resource key={`${item.type}:${item.id}`} item={item} onGo={onGo} onLink={setLinking}/>)}</div>}{linking && <SourceResearchPicker source={linking} onClose={()=>setLinking(null)} onGo={onGo}/>}</div>;
}
